import { calculateRecipeNutrition, type IngredientNutritionMatch, type NutritionProvider } from '@cravekeep/domain';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Field, Screen, Title } from '@/components/ui';
import { useNutritionStore } from '@/data/nutrition-store';
import { searchFatSecretNutrition, searchPackagedNutrition, searchUsdaNutrition, type NutritionCandidate } from '@/data/nutrition-api';
import { useRecipeStore } from '@/data/recipe-store';
import { colors, radii, spacing } from '@/theme';

const providers: { value: NutritionProvider; label: string; detail: string }[] = [
  { value: 'usda', label: 'USDA', detail: 'Generic ingredients' },
  { value: 'fatsecret', label: 'FatSecret', detail: 'Branded and serving gaps' },
  { value: 'open_food_facts', label: 'Open Food Facts', detail: 'Packaged foods' }
];
const value = (number: number | null) => number === null ? 'â€”' : Math.round(number * 10) / 10;

export default function RecipeNutritionScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { findRecipe } = useRecipeStore(); const recipe = findRecipe(id); const { findEstimate, saveEstimate } = useNutritionStore();
  const existing = findEstimate(id); const [matches, setMatches] = useState<IngredientNutritionMatch[]>(existing?.matches ?? []); const firstUnmatched = recipe?.ingredients.findIndex((ingredient) => !matches.some((match) => match.ingredientId === ingredient.id)) ?? -1;
  const [ingredientIndex, setIngredientIndex] = useState(firstUnmatched >= 0 ? firstUnmatched : 0); const ingredient = recipe?.ingredients[ingredientIndex]; const [provider, setProvider] = useState<NutritionProvider>('usda'); const [query, setQuery] = useState(ingredient?.name ?? ''); const [grams, setGrams] = useState('100'); const [results, setResults] = useState<NutritionCandidate[]>([]); const [selected, setSelected] = useState<NutritionCandidate>(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>();
  const estimate = useMemo(() => recipe ? calculateRecipeNutrition(recipe, matches) : undefined, [matches, recipe]);
  if (!recipe) return <Screen style={styles.center}><Title>Recipe unavailable</Title><Button label="Back to recipes" onPress={() => router.replace('/(tabs)/recipes')} /></Screen>;

  const chooseIngredient = (index: number) => { setIngredientIndex(index); setQuery(recipe.ingredients[index]?.name ?? ''); setResults([]); setSelected(undefined); setMessage(undefined); };
  const search = async () => { setBusy(true); setMessage(undefined); setSelected(undefined); try { const next = provider === 'usda' ? await searchUsdaNutrition(query) : provider === 'fatsecret' ? await searchFatSecretNutrition(query) : await searchPackagedNutrition(query); setResults(next); if (!next.length) setMessage('No confident matches found. Try a simpler food name or another provider.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Nutrition lookup failed.'); } finally { setBusy(false); } };
  const accept = () => {
    const weight = Number(grams); const basisGrams = selected?.basis === 'per_100g' ? 100 : selected?.servingQuantityGrams;
    if (!selected?.providerId || !basisGrams || !Number.isFinite(weight) || weight <= 0) { setMessage('Choose a result with a gram-based serving and enter the ingredient weight in grams.'); return; }
    const { calories, proteinGrams, carbohydrateGrams, fatGrams, sodiumMilligrams } = selected.nutrients;
    if ([calories, proteinGrams, carbohydrateGrams, fatGrams, sodiumMilligrams].some((amount) => amount === null)) { setMessage('This result is missing required nutrition values. Choose another result or provider.'); return; }
    const nutrients = { calories: calories!, proteinGrams: proteinGrams!, carbohydrateGrams: carbohydrateGrams!, fatGrams: fatGrams!, sodiumMilligrams: sodiumMilligrams! };
    const match: IngredientNutritionMatch = { ingredientId: ingredient!.id, ingredientName: ingredient!.name, provider: selected.provider, providerId: selected.providerId, servingId: selected.servingId ?? undefined, matchedName: selected.name, grams: weight, basisGrams, nutrients, confidence: selected.confidence };
    const next = [...matches.filter((item) => item.ingredientId !== ingredient!.id), match]; setMatches(next); const nextIndex = recipe.ingredients.findIndex((item) => !next.some((candidate) => candidate.ingredientId === item.id)); if (nextIndex >= 0) chooseIngredient(nextIndex); else { setResults([]); setSelected(undefined); setMessage('Every ingredient has a confirmed match. Review the estimate before saving.'); }
  };
  const save = async () => { if (!estimate?.matches.length) { setMessage('Match at least one ingredient before saving an estimate.'); return; } await saveEstimate(estimate); router.back(); };

  return <Screen><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={24} /></Pressable><Text style={styles.private}><Ionicons name="lock-closed" /> Private estimate</Text></View><Text style={styles.kicker}>NUTRITION REVIEW</Text><Title>Confirm what each ingredient means.</Title><Text style={styles.body}>Nutrition is an estimate. Confirm the food match and total grams used in the whole recipe; CraveKeep will never infer missing quantities as exact.</Text>
    <View style={styles.ingredientList}>{recipe.ingredients.map((item, index) => { const matched = matches.find((match) => match.ingredientId === item.id); return <Pressable accessibilityRole="button" accessibilityState={{ selected: index === ingredientIndex }} key={item.id} onPress={() => chooseIngredient(index)} style={[styles.ingredient, index === ingredientIndex && styles.ingredientActive]}><Ionicons color={matched ? colors.herb : colors.muted} name={matched ? 'checkmark-circle' : 'ellipse-outline'} size={20} /><View style={styles.flex}><Text style={styles.ingredientName}>{item.name}</Text><Text style={styles.small}>{matched ? `${matched.matchedName} Â· ${matched.grams} g` : 'Needs a match'}</Text></View></Pressable>; })}</View>
    {ingredient ? <Card style={styles.matcher}><Text style={styles.cardTitle}>Match: {ingredient.name}</Text><View style={styles.providerRow}>{providers.map((item) => <Pressable accessibilityRole="button" accessibilityState={{ selected: provider === item.value }} key={item.value} onPress={() => { setProvider(item.value); setResults([]); setSelected(undefined); }} style={[styles.provider, provider === item.value && styles.providerActive]}><Text style={[styles.providerText, provider === item.value && styles.providerTextActive]}>{item.label}</Text></Pressable>)}</View><Text style={styles.small}>{providers.find((item) => item.value === provider)?.detail}</Text><Field autoCapitalize="none" label="Food search" value={query} onChangeText={setQuery} /><Button disabled={busy || query.trim().length < 2} label={busy ? 'Searchingâ€¦' : 'Search provider'} onPress={() => void search()} />
      {busy ? <ActivityIndicator color={colors.coral} /> : results.map((candidate) => <Pressable accessibilityRole="button" accessibilityState={{ selected: selected === candidate }} key={`${candidate.provider}-${candidate.providerId}`} onPress={() => setSelected(candidate)} style={[styles.result, selected === candidate && styles.resultActive]}><View style={styles.flex}><Text style={styles.resultTitle}>{candidate.name}</Text><Text style={styles.small}>{candidate.brand || candidate.attribution} Â· {candidate.servingLabel || candidate.basis.replace('_', ' ')}</Text><Text style={styles.metrics}>{value(candidate.nutrients.calories)} cal Â· {value(candidate.nutrients.proteinGrams)}g protein Â· {value(candidate.nutrients.sodiumMilligrams)}mg sodium</Text></View><Ionicons color={selected === candidate ? colors.coral : colors.muted} name={selected === candidate ? 'radio-button-on' : 'radio-button-off'} size={22} /></Pressable>)}
      {selected ? <><Field keyboardType="decimal-pad" label={`Total grams of ${ingredient.name} in this recipe`} value={grams} onChangeText={setGrams} /><Button label="Confirm this match" onPress={accept} /></> : null}</Card> : null}
    {message ? <Text accessibilityRole="alert" style={styles.message}>{message}</Text> : null}
    {estimate ? <Card style={styles.summary}><Text style={styles.cardTitle}>Current estimate per serving</Text><View style={styles.metricGrid}><Text style={styles.metricBig}>{estimate.perServing.calories} cal</Text><Text style={styles.metricBig}>{estimate.perServing.proteinGrams}g protein</Text><Text style={styles.metricBig}>{estimate.perServing.carbohydrateGrams}g carbs</Text><Text style={styles.metricBig}>{estimate.perServing.fatGrams}g fat</Text><Text style={styles.metricBig}>{estimate.perServing.sodiumMilligrams}mg sodium</Text></View><Text style={styles.confidence}>{Math.round(estimate.coverage * 100)}% ingredient coverage Â· {estimate.confidence} confidence</Text><Text style={styles.small}>{estimate.servingAssumption}</Text></Card> : null}
    <Button label="Save nutrition estimate" onPress={() => void save()} />
  </ScrollView></Screen>;
}

const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.md, paddingBottom: 60 }, center: { padding: spacing.lg, justifyContent: 'center', gap: spacing.md }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, private: { color: colors.herb, fontWeight: '800' }, kicker: { color: colors.coralDark, fontWeight: '900', letterSpacing: 1.2 }, body: { color: colors.muted, lineHeight: 21 }, ingredientList: { gap: spacing.sm }, ingredient: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radii.medium, backgroundColor: colors.paperRaised }, ingredientActive: { borderColor: colors.coral }, flex: { flex: 1, gap: 3 }, ingredientName: { color: colors.charcoal, fontWeight: '800' }, small: { color: colors.muted, fontSize: 12, lineHeight: 17 }, matcher: { gap: spacing.md }, cardTitle: { color: colors.charcoal, fontSize: 18, fontWeight: '900' }, providerRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, provider: { paddingHorizontal: spacing.md, paddingVertical: 9, borderRadius: radii.round, borderWidth: 1, borderColor: colors.line }, providerActive: { backgroundColor: colors.coral, borderColor: colors.coral }, providerText: { color: colors.charcoal, fontWeight: '800' }, providerTextActive: { color: colors.white }, result: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radii.small }, resultActive: { borderColor: colors.coral, backgroundColor: colors.coral === colors.coral ? colors.lavenderSoft : colors.lavenderSoft }, resultTitle: { color: colors.charcoal, fontWeight: '800' }, metrics: { color: colors.herb, fontSize: 12, fontWeight: '700' }, message: { padding: spacing.md, color: colors.coralDark, backgroundColor: '#FFF0ED', borderRadius: radii.small }, summary: { gap: spacing.md, backgroundColor: colors.mintSoft }, metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, metricBig: { color: colors.charcoal, fontSize: 16, fontWeight: '900' }, confidence: { color: colors.herb, fontWeight: '900', textTransform: 'capitalize' } });
