import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Eyebrow, Screen, SectionTitle, Title } from '@/components/ui';
import { useRecipeStore } from '@/data/recipe-store';
import { useAuthStore } from '@/data/auth-store';
import { colors, radii, spacing, typography } from '@/theme';

const targets = [{ label: 'Calories', value: '1,650', unit: 'kcal', color: colors.coral, soft: '#FFF0ED' }, { label: 'Protein', value: '140', unit: 'g', color: colors.mint, soft: colors.mintSoft }, { label: 'Carbs', value: '165', unit: 'g', color: colors.lemon, soft: colors.lemonSoft }, { label: 'Fat', value: '55', unit: 'g', color: colors.lavender, soft: colors.lavenderSoft }];

export default function HomeScreen() {
  const { recipes, ready, error } = useRecipeStore(); const { user } = useAuthStore(); const latest = recipes[0];
  const displayName = user?.user_metadata.display_name as string | undefined; const firstName = displayName?.split(/\s+/)[0] ?? 'there'; const initials = (displayName ?? user?.email ?? 'CK').slice(0, 2).toUpperCase();
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View style={styles.flex}><Eyebrow>CRAVEKEEP</Eyebrow><Title>Good evening, {firstName}.</Title><Text style={styles.subtitle}>Let’s make dinner feel easy.</Text></View><Pressable accessibilityLabel='Open profile' accessibilityRole='button' onPress={() => router.push('/profile')} style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></Pressable></View>
    {error ? <Text accessibilityRole='alert' style={styles.error}>{error}</Text> : null}
    <Card style={styles.hero}><View style={styles.heroCopy}><Text style={styles.heroKicker}>TONIGHT'S IDEA</Text><View style={styles.heroRow}><View style={styles.heroCopy}><Text style={styles.heroTitle}>What’s for dinner?</Text><MotionSlot name="mascot-evening" size={86} accessibilityLabel="Animated dinner mascot" /></View></View><Text style={styles.heroBody}>Build a plan around recipes you already love.</Text><Pressable onPress={() => router.push('/(tabs)/plan')} style={styles.heroButton}><Text style={styles.heroButtonText}>Plan my week</Text><Ionicons color={colors.white} name='arrow-forward' size={18} /></Pressable></View><View style={styles.heroOrb}><Ionicons color={colors.coral} name='restaurant' size={44} /></View></Card>
    <SectionTitle action={<Pressable onPress={() => router.push('/onboarding/nutrition-goals')}><Text style={styles.link}>Edit goals</Text></Pressable>}>Today’s targets</SectionTitle>
    <View style={styles.targetRow}>{targets.map((target) => <View key={target.label} style={[styles.target, { backgroundColor: target.soft }]}><Text style={styles.targetLabel}>{target.label}</Text><Text style={styles.targetValue}>{target.value}</Text><Text style={styles.targetUnit}>{target.unit}</Text><View style={[styles.targetRing, { borderColor: target.color }]} /></View>)}</View>
    <SectionTitle>Quick actions</SectionTitle><View style={styles.actions}>{[['scan', 'Scan recipe', '/capture'], ['add', 'Add recipe', '/recipes/new'], ['calendar', 'Meal plan', '/(tabs)/plan'], ['basket', 'Groceries', '/(tabs)/groceries']].map(([icon, label, href]) => <Pressable key={label} accessibilityRole='button' onPress={() => router.push(href as never)} style={styles.action}><View style={styles.actionIcon}><Ionicons color={colors.coral} name={icon as keyof typeof Ionicons.glyphMap} size={21} /></View><Text style={styles.actionText}>{label}</Text></Pressable>)}</View>
    {!ready ? <ActivityIndicator color={colors.coral} /> : latest ? <><SectionTitle action={<Pressable onPress={() => router.push('/(tabs)/recipes')}><Text style={styles.link}>See all</Text></Pressable>}>Recently saved</SectionTitle><Pressable onPress={() => router.push(`/recipes/${latest.id}`)}><Card><View style={styles.recipeRow}><View style={styles.recipeIcon}><Ionicons color={colors.coral} name='flame' size={26} /></View><View style={styles.flex}><Text style={styles.recipeTitle}>{latest.title}</Text><Text style={styles.body}>{latest.prepMinutes + latest.cookMinutes} min · {latest.servings} servings</Text><Text style={styles.source}>{latest.source.label} · Private</Text></View><Ionicons color={colors.muted} name='chevron-forward' size={22} /></View></Card></Pressable></> : <Card style={styles.empty}><Ionicons color={colors.mint} name='sparkles-outline' size={38} /><Text style={styles.recipeTitle}>Your kitchen starts here.</Text><Text style={styles.body}>Add a recipe to start building your personal collection.</Text></Card>}
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({
  content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 110 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  flex: { flex: 1, gap: 3 }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.charcoal, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontWeight: '800' }, subtitle: { color: colors.muted, fontSize: 14 },
  hero: { flexDirection: 'row', alignItems: 'center', minHeight: 190, backgroundColor: colors.coral, overflow: 'hidden', borderWidth: 0 }, heroCopy: { flex: 1, gap: spacing.sm }, heroKicker: { color: '#FFE5DF', fontSize: 11, fontWeight: '900', letterSpacing: 1.1 }, heroTitle: { color: colors.white, ...typography.title, fontSize: 28, lineHeight: 32 }, heroBody: { color: '#FFF1ED', fontSize: 14, lineHeight: 20 }, heroButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 14, paddingVertical: 10, borderRadius: radii.round, backgroundColor: colors.charcoal }, heroButtonText: { color: colors.white, fontWeight: '800' }, heroOrb: { width: 92, height: 92, borderRadius: 46, backgroundColor: colors.lemon, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '12deg' }] },
  targetRow: { flexDirection: 'row', gap: spacing.sm }, target: { flex: 1, minHeight: 112, borderRadius: radii.medium, padding: spacing.sm, overflow: 'hidden' }, targetLabel: { color: colors.charcoal, fontSize: 10, fontWeight: '800' }, targetValue: { color: colors.charcoal, fontSize: 20, fontWeight: '900', marginTop: 9 }, targetUnit: { color: colors.muted, fontSize: 10 }, targetRing: { position: 'absolute', width: 42, height: 42, borderRadius: 21, borderWidth: 5, right: -8, bottom: -8, opacity: 0.9 },
  actions: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, action: { flex: 1, alignItems: 'center', gap: 7 }, actionIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, actionText: { color: colors.charcoal, fontSize: 11, fontWeight: '800', textAlign: 'center' },
  link: { color: colors.coralDark, fontWeight: '800' }, recipeRow: { flexDirection: 'row', gap: spacing.md, alignItems: 'center' }, recipeIcon: { width: 54, height: 54, borderRadius: radii.medium, backgroundColor: colors.lemonSoft, alignItems: 'center', justifyContent: 'center' }, recipeTitle: { color: colors.charcoal, fontSize: 17, fontWeight: '800' }, body: { color: colors.muted, fontSize: 14, lineHeight: 20 }, source: { color: colors.mint, fontSize: 12, fontWeight: '700' }, error: { color: colors.coralDark, backgroundColor: '#FFF0ED', padding: spacing.md, borderRadius: radii.medium }, empty: { alignItems: 'center', gap: spacing.sm }
});