import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MotionSlot } from '@/components/animations/MotionSlot';
import { Card, Eyebrow, Screen, SectionTitle, Title } from '@/components/ui';
import { useRecipeStore } from '@/data/recipe-store';
import { useAuthStore } from '@/data/auth-store';
import { useOnboardingStore } from '@/data/onboarding-store';
import { colors, radii, spacing, typography } from '@/theme';
import { RecipeArt } from '@/components/recipe-art';
import brandLogo from '../../assets/brand/welcome-logo-lockup.png';

export default function HomeScreen() {
  const { recipes, ready, error } = useRecipeStore(); const { user } = useAuthStore(); const { profile } = useOnboardingStore(); const latest = recipes[0];
  const dailyTargets = [{ label: 'Calories', value: profile.calories.toLocaleString(), unit: 'kcal', color: colors.coral, soft: '#FFF0ED' }, { label: 'Protein', value: profile.protein.replace(/[^0-9]/g, '') || '—', unit: 'g', color: colors.mint, soft: colors.mintSoft }, { label: 'Carbs', value: profile.carbs.replace(/[^0-9]/g, '') || '—', unit: 'g', color: colors.lemon, soft: colors.lemonSoft }, { label: 'Fat', value: profile.fat.replace(/[^0-9]/g, '') || '—', unit: 'g', color: colors.lavender, soft: colors.lavenderSoft }];
  const displayName = user?.user_metadata.display_name as string | undefined; const firstName = displayName?.split(/\s+/)[0] ?? 'there'; const initials = (displayName ?? user?.email ?? 'CK').slice(0, 2).toUpperCase();
  const hour = new Date().getHours();
  const timeOfDay = hour < 12 ? 'morning' : hour < 17 ? 'afternoon' : 'evening';
  const greeting = timeOfDay === 'morning' ? 'Good morning' : timeOfDay === 'afternoon' ? 'Good afternoon' : 'Good evening';
  const sceneTitle = timeOfDay === 'morning' ? 'Start with something delicious.' : timeOfDay === 'afternoon' ? 'Make tonight easier.' : 'Let’s make dinner feel easy.';
  const scenePrompt = timeOfDay === 'morning' ? 'Plan a bright start with recipes you already love.' : timeOfDay === 'afternoon' ? 'Save an idea now and make tonight effortless.' : 'Build a plan around recipes you already love.';
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={[styles.welcome, timeOfDay === 'morning' ? styles.morningWelcome : timeOfDay === 'afternoon' ? styles.afternoonWelcome : styles.eveningWelcome]}>
      <View style={styles.welcomeSky} pointerEvents="none">
        <View style={[styles.welcomeSun, timeOfDay === 'evening' && styles.welcomeMoon]} />
        <View style={styles.welcomeCloudOne} />
        <View style={styles.welcomeCloudTwo} />
        <View style={styles.welcomeHillBack} />
        <View style={styles.welcomeHillFront} />
        {timeOfDay === 'evening' ? <><Ionicons color="#FFF3B0" name="star" size={10} style={styles.starOne} /><Ionicons color="#FFF3B0" name="star" size={7} style={styles.starTwo} /></> : null}
      </View>
      <View style={styles.header}><Image accessibilityLabel="CraveKeep" resizeMode="contain" source={brandLogo} style={[styles.logo, timeOfDay === 'evening' && styles.logoEvening]} /><View style={styles.headerActions}><Pressable accessibilityLabel='Open notifications' accessibilityRole='button' onPress={() => router.push('/notifications')} style={[styles.iconButton, styles.overlayButton]}><Ionicons color={timeOfDay === 'evening' ? colors.white : colors.charcoal} name='notifications-outline' size={20} /></Pressable><Pressable accessibilityLabel='Open profile' accessibilityRole='button' onPress={() => router.push('/profile')} style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></Pressable></View></View>
      <View style={styles.welcomeCopy}><Text style={[styles.welcomeGreeting, timeOfDay === 'evening' && styles.lightText]}>{greeting}, {firstName}.</Text><Text style={[styles.welcomeSubtitle, timeOfDay === 'evening' && styles.lightMuted]}>{sceneTitle}</Text></View>
    </View>
    {error ? <Text accessibilityRole='alert' style={styles.error}>{error}</Text> : null}
    <Pressable accessibilityRole="button" onPress={() => router.push('/(tabs)/plan')} style={styles.hero}><View style={styles.heroContent}><Text style={styles.heroKicker}>TONIGHT’S IDEA</Text><Text style={styles.heroTitle}>What’s for dinner?</Text><Text style={styles.heroBody}>{scenePrompt}</Text><View style={styles.heroButton}><Text style={styles.heroButtonText}>Plan my week</Text><Ionicons color={colors.white} name='arrow-forward' size={18} /></View></View><View style={styles.heroOrb}><Ionicons color={colors.coral} name='restaurant' size={40} /></View><MotionSlot name={timeOfDay === 'evening' ? 'mascot-evening' : 'onboarding-recipe-card'} size={78} accessibilityLabel="Animated CraveKeep helper" style={styles.heroMascot} /></Pressable>
    <Pressable accessibilityRole='button' onPress={() => router.push('/discover')} style={styles.discover}><View style={styles.discoverIcon}><Ionicons color={colors.white} name='sparkles' size={20} /></View><View style={styles.flex}><Text style={styles.discoverTitle}>Discover something new</Text><Text style={styles.body}>Personalized recipes for tonight and beyond.</Text></View><Ionicons color={colors.coralDark} name='arrow-forward' size={18} /></Pressable>
    <SectionTitle action={<Pressable onPress={() => router.push('/nutrition')}><Text style={styles.link}>View nutrition</Text></Pressable>}>Today’s targets</SectionTitle>
    <View style={styles.targetRow}>{dailyTargets.map((target) => <View key={target.label} style={[styles.target, { backgroundColor: target.soft }]}><Text style={styles.targetLabel}>{target.label}</Text><Text style={styles.targetValue}>{target.value}</Text><Text style={styles.targetUnit}>{target.unit}</Text><View style={[styles.targetRing, { borderColor: target.color }]} /></View>)}</View>
    <SectionTitle>Quick actions</SectionTitle><View style={styles.actions}>{[['scan', 'Scan recipe', '/capture'], ['add', 'Add recipe', '/recipes/new'], ['calendar', 'Meal plan', '/(tabs)/plan'], ['basket', 'Groceries', '/(tabs)/groceries']].map(([icon, label, href]) => <Pressable key={label} accessibilityRole='button' onPress={() => router.push(href as never)} style={styles.action}><View style={styles.actionIcon}><Ionicons color={colors.coral} name={icon as keyof typeof Ionicons.glyphMap} size={21} /></View><Text style={styles.actionText}>{label}</Text></Pressable>)}</View>
    {!ready ? <ActivityIndicator color={colors.coral} /> : latest ? <><SectionTitle action={<Pressable onPress={() => router.push('/(tabs)/recipes')}><Text style={styles.link}>See all</Text></Pressable>}>Recently saved</SectionTitle><Pressable onPress={() => router.push(`/recipes/${latest.id}`)}><Card><View style={styles.recipeRow}>{latest.source.imageUrl || latest.source.storagePath ? <RecipeArt compact imageUrl={latest.source.imageUrl} storagePath={latest.source.storagePath} /> : <View style={styles.recipeIcon}><Ionicons color={colors.coral} name='flame' size={26} /></View>}<View style={styles.flex}><Text style={styles.recipeTitle}>{latest.title}</Text><Text style={styles.body}>{latest.prepMinutes + latest.cookMinutes} min · {latest.servings} servings</Text><Text style={styles.source}>{latest.source.label} · Private</Text></View><Ionicons color={colors.muted} name='chevron-forward' size={22} /></View></Card></Pressable></> : <Card style={styles.empty}><Ionicons color={colors.mint} name='sparkles-outline' size={38} /><Text style={styles.recipeTitle}>Your kitchen starts here.</Text><Text style={styles.body}>Add a recipe to start building your personal collection.</Text></Card>}
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({
  content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 110 }, welcome: { minHeight: 190, borderRadius: radii.large, overflow: 'hidden', padding: spacing.lg, position: 'relative', justifyContent: 'space-between' }, morningWelcome: { backgroundColor: '#DDF2E9' }, afternoonWelcome: { backgroundColor: '#FFE0B8' }, eveningWelcome: { backgroundColor: '#172C49' }, welcomeSky: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' }, welcomeSun: { position: 'absolute', width: 72, height: 72, borderRadius: 36, right: 34, top: 58, backgroundColor: '#FFD86B' }, welcomeMoon: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#FFF3B0', shadowColor: '#FFF3B0', shadowOpacity: 0.45, shadowRadius: 14 }, welcomeCloudOne: { position: 'absolute', width: 88, height: 28, borderRadius: 20, right: 88, top: 100, backgroundColor: 'rgba(255,255,255,0.42)' }, welcomeCloudTwo: { position: 'absolute', width: 58, height: 20, borderRadius: 18, left: 34, top: 82, backgroundColor: 'rgba(255,255,255,0.3)' }, welcomeHillBack: { position: 'absolute', width: 260, height: 105, borderRadius: 130, left: -36, bottom: -62, backgroundColor: '#91C5A6', opacity: 0.8 }, welcomeHillFront: { position: 'absolute', width: 300, height: 120, borderRadius: 150, right: -90, bottom: -76, backgroundColor: '#5C9A7B', opacity: 0.9 }, starOne: { position: 'absolute', right: 118, top: 65 }, starTwo: { position: 'absolute', right: 72, top: 38 }, header: { zIndex: 3, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md }, logo: { width: 132, height: 38 }, logoEvening: { backgroundColor: 'rgba(255,255,255,0.92)', borderRadius: 10, paddingHorizontal: 5 }, headerActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, iconButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, overlayButton: { backgroundColor: 'rgba(255,255,255,0.16)', borderColor: 'rgba(255,255,255,0.35)' }, welcomeCopy: { zIndex: 3, gap: 4, paddingTop: spacing.lg, maxWidth: '78%' }, welcomeGreeting: { color: colors.charcoal, fontSize: 28, lineHeight: 32, fontWeight: '900', letterSpacing: -0.7 }, welcomeSubtitle: { color: '#41524B', fontSize: 14, lineHeight: 20, fontWeight: '600' }, lightText: { color: colors.white }, lightMuted: { color: '#D9E5F2' },
  flex: { flex: 1, gap: 3 }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.charcoal, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontWeight: '800' }, subtitle: { color: colors.muted, fontSize: 14 },
  hero: { minHeight: 224, borderRadius: radii.large, overflow: 'hidden', borderWidth: 0, padding: spacing.lg, position: 'relative', backgroundColor: colors.coral, shadowColor: colors.coralDark, shadowOpacity: 0.16, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, heroContent: { zIndex: 3, width: '76%', gap: spacing.sm }, heroKicker: { color: '#FFF1E8', fontSize: 11, fontWeight: '900', letterSpacing: 1.1 }, heroTitle: { color: colors.white, ...typography.title, fontSize: 28, lineHeight: 32 }, heroBody: { color: '#FFF8F2', fontSize: 14, lineHeight: 20 }, heroButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 14, paddingVertical: 10, borderRadius: radii.round, backgroundColor: colors.charcoal }, heroButtonText: { color: colors.white, fontWeight: '800' }, heroOrb: { position: 'absolute', zIndex: 4, width: 76, height: 76, borderRadius: 38, right: 18, top: 32, backgroundColor: colors.lemon, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '10deg' }] }, heroMascot: { position: 'absolute', zIndex: 5, right: 6, bottom: -2 },
  discover: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radii.medium, backgroundColor: colors.lavenderSoft }, discoverIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.coral }, discoverTitle: { color: colors.charcoal, fontSize: 16, fontWeight: '900' }, community: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radii.medium, backgroundColor: colors.coralSoft }, communityIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.coral },
  targetRow: { flexDirection: 'row', gap: spacing.sm }, target: { flex: 1, minHeight: 112, borderRadius: radii.medium, padding: spacing.sm, overflow: 'hidden' }, targetLabel: { color: colors.charcoal, fontSize: 10, fontWeight: '800' }, targetValue: { color: colors.charcoal, fontSize: 20, fontWeight: '900', marginTop: 9 }, targetUnit: { color: colors.muted, fontSize: 10 }, targetRing: { position: 'absolute', width: 42, height: 42, borderRadius: 21, borderWidth: 5, right: -8, bottom: -8, opacity: 0.9 },
  actions: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, action: { flex: 1, alignItems: 'center', gap: 7 }, actionIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, actionText: { color: colors.charcoal, fontSize: 11, fontWeight: '800', textAlign: 'center' },
  link: { color: colors.coralDark, fontWeight: '800' }, recipeRow: { flexDirection: 'row', gap: spacing.md, alignItems: 'center' }, recipeIcon: { width: 54, height: 54, borderRadius: radii.medium, backgroundColor: colors.lemonSoft, alignItems: 'center', justifyContent: 'center' }, recipeTitle: { color: colors.charcoal, fontSize: 17, fontWeight: '800' }, body: { color: colors.muted, fontSize: 14, lineHeight: 20 }, source: { color: colors.mint, fontSize: 12, fontWeight: '700' }, error: { color: colors.coralDark, backgroundColor: '#FFF0ED', padding: spacing.md, borderRadius: radii.medium }, empty: { alignItems: 'center', gap: spacing.sm }
});