import { summarizePlannedDay, type DailyNutritionTargets, type MealSlot } from '@cravekeep/domain';
import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Eyebrow, Field, Screen, SectionTitle, Title } from '@/components/ui';
import { useNutritionStore } from '@/data/nutrition-store';
import { usePlanningStore } from '@/data/planning-store';
import { useRecipeStore } from '@/data/recipe-store';
import { colors, radii, spacing } from '@/theme';

const slots: MealSlot[] = ['breakfast', 'lunch', 'dinner', 'snack'];
const targetFields: { key: keyof DailyNutritionTargets; label: string; unit: string }[] = [
  { key: 'calories', label: 'Calories', unit: 'cal' }, { key: 'proteinGrams', label: 'Protein', unit: 'g' },
  { key: 'carbohydrateGrams', label: 'Carbohydrates', unit: 'g' }, { key: 'fatGrams', label: 'Fat', unit: 'g' },
  { key: 'sodiumMilligrams', label: 'Sodium', unit: 'mg' }
];
const toLocalDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const weekDates = () => Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setDate(date.getDate() + offset); return { value: toLocalDate(date), weekday: date.toLocaleDateString(undefined, { weekday: 'short' }), day: date.getDate() }; });

export default function PlanScreen() {
  const { recipes } = useRecipeStore(); const { estimates } = useNutritionStore();
  const { targets, meals, updateTargets, addMeal, toggleMealStatus, updateMealServings, removeMeal, error } = usePlanningStore();
  const dates = useMemo(weekDates, []); const [selectedDate, setSelectedDate] = useState(dates[0]!.value); const [slot, setSlot] = useState<MealSlot>('dinner'); const [message, setMessage] = useState<string>();
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(targetFields.map((field) => [field.key, targets ? String(targets[field.key]) : ''])));
  useEffect(() => { if (targets) setValues(Object.fromEntries(targetFields.map((field) => [field.key, String(targets[field.key])]))); }, [targets]);
  const selectedMeals = useMemo(() => meals.filter((meal) => meal.date === selectedDate), [meals, selectedDate]);
  const summary = useMemo(() => targets ? summarizePlannedDay(selectedMeals, estimates, targets) : null, [estimates, selectedMeals, targets]);
  const candidates = useMemo(() => recipes.map((recipe) => ({ recipe, estimate: estimates.find((item) => item.recipeId === recipe.id) })).filter((item) => item.estimate), [estimates, recipes]);
  const saveTargets = async () => { const next = Object.fromEntries(targetFields.map((field) => [field.key, Number(values[field.key])])) as DailyNutritionTargets; if (Object.values(next).some((value) => !Number.isFinite(value) || value < 0)) { setMessage('Enter zero or a positive number for every target.'); return; } await updateTargets(next); setMessage('Daily targets saved.'); };

  return <Screen><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    <Eyebrow>WEEKLY PLAN</Eyebrow><Title>Plan around food you enjoy.</Title><Text style={styles.body}>Planned and eaten values stay separate. Nutrition remains an estimate based on confirmed ingredient matches.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days}>{dates.map((date, index) => <Pressable accessibilityRole="button" accessibilityState={{ selected: selectedDate === date.value }} key={date.value} onPress={() => setSelectedDate(date.value)} style={[styles.day, selectedDate === date.value && styles.dayActive]}><Text style={[styles.dayName, selectedDate === date.value && styles.dayTextActive]}>{index === 0 ? 'Today' : date.weekday}</Text><Text style={[styles.dayNumber, selectedDate === date.value && styles.dayTextActive]}>{date.day}</Text></Pressable>)}</ScrollView>
    <Card style={styles.targets}><SectionTitle>Daily targets</SectionTitle><View style={styles.targetGrid}>{targetFields.map((field) => <View key={field.key} style={styles.targetField}><Field keyboardType="decimal-pad" label={`${field.label} (${field.unit})`} value={values[field.key] ?? ''} onChangeText={(value) => setValues((current) => ({ ...current, [field.key]: value }))} /></View>)}</View><Button label="Save targets" onPress={() => void saveTargets()} /></Card>
    {summary ? <Card style={styles.summary}><SectionTitle>Selected day</SectionTitle><View style={styles.summaryRow}><View><Text style={styles.summaryLabel}>EATEN</Text><Text style={styles.summaryValue}>{summary.eaten.calories} cal</Text></View><View><Text style={styles.summaryLabel}>PLANNED</Text><Text style={styles.summaryValue}>{summary.planned.calories} cal</Text></View><View><Text style={styles.summaryLabel}>REMAINING</Text><Text style={[styles.summaryValue, summary.remaining.calories < 0 && styles.over]}>{summary.remaining.calories} cal</Text></View></View><Text style={styles.macros}>{summary.remaining.proteinGrams}g protein · {summary.remaining.carbohydrateGrams}g carbs · {summary.remaining.fatGrams}g fat remaining</Text>{summary.missingEstimateCount ? <Text style={styles.warning}>{summary.missingEstimateCount} meal(s) excluded because nutrition has not been confirmed.</Text> : null}</Card> : null}
    <SectionTitle>Meals</SectionTitle>{selectedMeals.length ? selectedMeals.map((meal) => { const recipe = recipes.find((item) => item.id === meal.recipeId); return <View key={meal.id} style={styles.meal}><Pressable accessibilityLabel={`Mark ${recipe?.title ?? 'meal'} as ${meal.status === 'planned' ? 'eaten' : 'planned'}`} accessibilityRole="button" onPress={() => void toggleMealStatus(meal.id)}><Ionicons color={meal.status === 'eaten' ? colors.herb : colors.citrus} name={meal.status === 'eaten' ? 'checkmark-circle' : 'time-outline'} size={26} /></Pressable><View style={styles.flex}><Text style={styles.mealTitle}>{recipe?.title ?? 'Recipe unavailable'}</Text><Text style={styles.small}>{meal.slot} · {meal.servings} serving · {meal.status}</Text></View><View style={styles.controls}><Pressable accessibilityLabel="Decrease serving" disabled={meal.servings <= 0.25} onPress={() => void updateMealServings(meal.id, meal.servings - 0.25)} style={styles.iconButton}><Ionicons name="remove" size={18} /></Pressable><Pressable accessibilityLabel="Increase serving" onPress={() => void updateMealServings(meal.id, meal.servings + 0.25)} style={styles.iconButton}><Ionicons name="add" size={18} /></Pressable><Pressable accessibilityLabel={`Remove ${recipe?.title ?? 'meal'}`} onPress={() => void removeMeal(meal.id)} style={styles.iconButton}><Ionicons color={colors.coralDark} name="trash-outline" size={18} /></Pressable></View></View>; }) : <Text style={styles.body}>Nothing planned for this day.</Text>}
    <SectionTitle>Add a meal</SectionTitle><View style={styles.slotRow}>{slots.map((item) => <Pressable accessibilityRole="button" accessibilityState={{ selected: slot === item }} key={item} onPress={() => setSlot(item)} style={[styles.slot, slot === item && styles.slotActive]}><Text style={[styles.slotText, slot === item && styles.slotTextActive]}>{item}</Text></Pressable>)}</View>
    {candidates.map(({ recipe, estimate }) => <Card key={recipe.id} style={styles.candidate}><View style={styles.flex}><Text style={styles.mealTitle}>{recipe.title}</Text><Text style={styles.small}>{estimate!.perServing.calories} cal · {estimate!.perServing.proteinGrams}g protein per serving</Text></View><Button label={`Add to ${slot}`} variant="secondary" onPress={() => void addMeal(selectedDate, slot, recipe.id, 1)} /></Card>)}{!candidates.length ? <Text style={styles.body}>Calculate nutrition for a recipe before adding it to the plan.</Text> : null}
    {message || error ? <Text accessibilityRole="alert" style={styles.message}>{message ?? error}</Text> : null}
  </ScrollView></Screen>;
}

const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.md, paddingBottom: 100 }, body: { color: colors.muted, lineHeight: 22 }, days: { gap: spacing.sm }, day: { width: 64, alignItems: 'center', padding: spacing.sm, borderRadius: radii.medium, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.paperRaised }, dayActive: { backgroundColor: colors.coral, borderColor: colors.coral }, dayName: { color: colors.muted, fontSize: 12, fontWeight: '800' }, dayNumber: { color: colors.charcoal, fontSize: 20, fontWeight: '900' }, dayTextActive: { color: colors.white }, targets: { gap: spacing.md }, targetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, targetField: { minWidth: 140, flex: 1 }, summary: { gap: spacing.md, backgroundColor: colors.herbSoft }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, summaryLabel: { color: colors.muted, fontSize: 10, fontWeight: '900' }, summaryValue: { color: colors.charcoal, fontSize: 18, fontWeight: '900' }, over: { color: colors.coralDark }, macros: { color: colors.herb, fontWeight: '800' }, warning: { color: colors.coralDark, lineHeight: 20 }, meal: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radii.medium, backgroundColor: colors.paperRaised }, flex: { flex: 1 }, mealTitle: { color: colors.charcoal, fontSize: 16, fontWeight: '900' }, small: { color: colors.muted, fontSize: 13, textTransform: 'capitalize' }, controls: { flexDirection: 'row', gap: 4 }, iconButton: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: colors.paper }, slotRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, slot: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radii.round, borderWidth: 1, borderColor: colors.line }, slotActive: { backgroundColor: colors.coral, borderColor: colors.coral }, slotText: { color: colors.charcoal, fontWeight: '800', textTransform: 'capitalize' }, slotTextActive: { color: colors.white }, candidate: { gap: spacing.sm }, message: { color: colors.coralDark, fontWeight: '700' } });
