import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, Eyebrow, Screen, Title } from '@/components/ui';
import { useRecipeStore } from '@/data/recipe-store';
import { useAuthStore } from '@/data/auth-store';
import { colors, radii, spacing } from '@/theme';
import { RecipeArt } from '@/components/recipe-art';

export default function RecipesScreen() {
  const { recipes, ready } = useRecipeStore();
  const { user } = useAuthStore();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'favorites' | 'versions'>('all');
  const [communitySavedCount, setCommunitySavedCount] = useState(0);
  const [communitySavedTitles, setCommunitySavedTitles] = useState<string[]>([]);
  const initials = (user?.user_metadata.display_name || user?.email || 'CK').slice(0, 2).toUpperCase();
  const loadCommunitySaves = useCallback(() => { void Promise.all([AsyncStorage.getItem('cravekeep.community.saves.v1'), AsyncStorage.getItem('cravekeep.community.posts.v1')]).then(([value, postsValue]) => { try { const saved = value ? JSON.parse(value) : []; const posts = postsValue ? JSON.parse(postsValue) : []; if (Array.isArray(saved)) { setCommunitySavedCount(saved.length); if (Array.isArray(posts)) setCommunitySavedTitles(posts.filter((post) => saved.includes(post.id)).slice(0, 3).map((post) => post.title)); } } catch { setCommunitySavedCount(0); setCommunitySavedTitles([]); } }); }, []);
  useFocusEffect(useCallback(() => { loadCommunitySaves(); }, [loadCommunitySaves]));
  const visibleRecipes = useMemo(() => {
    const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
    return recipes.filter((recipe) => {
      if (filter === 'favorites' && !recipe.favorite) return false;
      if (filter === 'versions' && recipe.version === 1) return false;
      const searchable = [recipe.title, recipe.description, recipe.source.label, ...recipe.ingredients.map((item) => item.name), ...recipe.steps].join(' ').toLocaleLowerCase();
      return terms.every((term) => searchable.includes(term));
    });
  }, [filter, query, recipes]);
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Eyebrow>YOUR COLLECTION</Eyebrow><Title>Recipes you’ll keep coming back to.</Title></View><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View></View>
    <View style={styles.search}><Ionicons color={colors.muted} name="search" size={20} /><TextInput accessibilityLabel="Search recipes" onChangeText={setQuery} placeholder="Title, ingredient, or direction" placeholderTextColor={colors.muted} returnKeyType="search" style={styles.searchInput} value={query} />{query ? <Pressable accessibilityLabel="Clear recipe search" onPress={() => setQuery('')}><Ionicons color={colors.muted} name="close-circle" size={20} /></Pressable> : null}</View>
    <View accessibilityRole="tablist" style={styles.filters}>{(['all', 'favorites', 'versions'] as const).map((value) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: filter === value }} key={value} onPress={() => setFilter(value)}><Text style={filter === value ? styles.filterActive : styles.filter}>{value === 'all' ? 'All' : value === 'favorites' ? 'Favorites' : 'Versions'}</Text></Pressable>)}</View>
    {communitySavedCount > 0 ? <Pressable accessibilityRole="button" onPress={() => router.push('/community')} style={styles.savedCommunity}><Ionicons color={colors.coral} name="bookmark" size={22} /><View style={styles.communityCopy}><Text style={styles.communityTitle}>{communitySavedCount} saved from Community</Text><Text style={styles.communityBody}>{communitySavedTitles.length ? communitySavedTitles.join(' · ') : 'Open Community to revisit your saved inspiration.'}</Text></View><Ionicons color={colors.coralDark} name="arrow-forward" size={18} /></Pressable> : null}<Pressable accessibilityRole="button" onPress={() => router.push('/community')} style={styles.community}><View style={styles.communityIcon}><Ionicons color={colors.white} name="people" size={19} /></View><View style={styles.communityCopy}><Text style={styles.communityTitle}>Need inspiration?</Text><Text style={styles.communityBody}>Browse recipes shared by the community.</Text></View><Ionicons color={colors.coralDark} name="arrow-forward" size={18} /></Pressable>
    {!ready ? <ActivityIndicator color={colors.coral} /> : recipes.length === 0 ? <Card style={styles.empty}><Ionicons color={colors.coral} name="book-outline" size={64} /><Text style={styles.emptyTitle}>Your recipes deserve one home.</Text><Text style={styles.body}>Create a recipe now, then capture from anywhere as those slices arrive.</Text><Button label="Add my first recipe" onPress={() => router.push('/recipes/new')} /></Card> : visibleRecipes.length === 0 ? <Card style={styles.empty}><Ionicons color={colors.herb} name="search-outline" size={48} /><Text style={styles.emptyTitle}>No recipes match.</Text><Text style={styles.body}>Try fewer words or choose a different filter.</Text><Button label="Clear search and filters" onPress={() => { setQuery(''); setFilter('all'); }} /></Card> : <View style={styles.grid}>{visibleRecipes.map((recipe) => <Pressable accessibilityLabel={`Open ${recipe.title}`} key={recipe.id} onPress={() => router.push(`/recipes/${recipe.id}`)} style={styles.recipeCard}><RecipeArt compact favorite={recipe.favorite} /><Text numberOfLines={2} style={styles.recipeTitle}>{recipe.title}</Text><Text style={styles.body}>{recipe.prepMinutes + recipe.cookMinutes} min</Text><Text style={styles.badge}>{recipe.version > 1 ? `Version ${recipe.version}` : recipe.source.kind === 'manual' ? 'Original' : recipe.source.kind === 'imported' ? 'Imported' : 'Sample'}</Text></Pressable>)}</View>}
    <Button label="Create a recipe" onPress={() => router.push('/recipes/new')} />
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 110 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.charcoal, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontWeight: '800' }, search: { height: 50, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radii.small, paddingHorizontal: spacing.md, backgroundColor: colors.paperRaised }, searchInput: { flex: 1, fontSize: 16, color: colors.charcoal }, filters: { flexDirection: 'row', gap: spacing.sm }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radii.round, color: colors.muted, borderWidth: 1, borderColor: colors.line }, filterActive: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radii.round, color: colors.white, backgroundColor: colors.coral, overflow: 'hidden' }, community: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: radii.medium, backgroundColor: colors.coralSoft }, communityIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.coral }, communityCopy: { flex: 1, gap: 2 }, communityTitle: { color: colors.charcoal, fontWeight: '900', fontSize: 15 }, communityBody: { color: colors.muted, fontSize: 12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, recipeCard: { width: '47%', gap: 5 }, recipeArt: { height: 128, borderRadius: radii.medium, backgroundColor: colors.mintSoft, alignItems: 'center', justifyContent: 'center' }, heart: { position: 'absolute', right: 10, top: 10 }, recipeTitle: { color: colors.charcoal, fontSize: 16, lineHeight: 20, fontWeight: '800' }, body: { color: colors.muted, fontSize: 13, lineHeight: 19 }, badge: { alignSelf: 'flex-start', color: colors.herb, backgroundColor: colors.herbSoft, paddingHorizontal: 8, paddingVertical: 3, borderRadius: radii.round, fontSize: 11, fontWeight: '700' }, empty: { alignItems: 'center', gap: spacing.md }, emptyTitle: { fontFamily: 'System', fontSize: 24, color: colors.charcoal, fontWeight: '700', textAlign: 'center' } });
