import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, Screen, Title } from '@/components/ui';
import { useRecipeStore } from '@/data/recipe-store';
import { colors, radii, spacing } from '@/theme';

export default function RecipesScreen() {
  const { recipes, ready } = useRecipeStore();
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><Title>My Recipes</Title><View style={styles.avatar}><Text style={styles.avatarText}>JS</Text></View></View>
    <View style={styles.search}><Ionicons color={colors.muted} name="search" size={20} /><TextInput accessibilityLabel="Search recipes" placeholder="What are you craving?" placeholderTextColor={colors.muted} style={styles.searchInput} /></View>
    <View style={styles.filters}><Text style={styles.filterActive}>All</Text><Text style={styles.filter}>Favorites</Text><Text style={styles.filter}>Cookbooks</Text></View>
    {!ready ? <ActivityIndicator color={colors.coral} /> : recipes.length === 0 ? <Card style={styles.empty}><Ionicons color={colors.coral} name="book-outline" size={64} /><Text style={styles.emptyTitle}>Your recipes deserve one home.</Text><Text style={styles.body}>Create a recipe now, then capture from anywhere as those slices arrive.</Text><Button label="Add my first recipe" onPress={() => router.push('/recipes/new')} /></Card> : <View style={styles.grid}>{recipes.map((recipe) => <Pressable key={recipe.id} onPress={() => router.push(`/recipes/${recipe.id}`)} style={styles.recipeCard}><View style={styles.recipeArt}><Ionicons color={colors.herb} name="leaf" size={38} />{recipe.favorite ? <Ionicons color={colors.coral} name="heart" size={19} style={styles.heart} /> : null}</View><Text numberOfLines={2} style={styles.recipeTitle}>{recipe.title}</Text><Text style={styles.body}>{recipe.prepMinutes + recipe.cookMinutes} min</Text><Text style={styles.badge}>{recipe.source.kind === 'manual' ? 'Original' : 'Sample'}</Text></Pressable>)}</View>}
    <Button label="Create a recipe" onPress={() => router.push('/recipes/new')} />
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 110 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.charcoal, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontWeight: '800' }, search: { height: 50, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radii.small, paddingHorizontal: spacing.md, backgroundColor: colors.paperRaised }, searchInput: { flex: 1, fontSize: 16, color: colors.charcoal }, filters: { flexDirection: 'row', gap: spacing.sm }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radii.round, color: colors.muted, borderWidth: 1, borderColor: colors.line }, filterActive: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radii.round, color: colors.white, backgroundColor: colors.coral, overflow: 'hidden' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, recipeCard: { width: '47%', gap: 5 }, recipeArt: { height: 128, borderRadius: radii.medium, backgroundColor: colors.herbSoft, alignItems: 'center', justifyContent: 'center' }, heart: { position: 'absolute', right: 10, top: 10 }, recipeTitle: { color: colors.charcoal, fontSize: 16, lineHeight: 20, fontWeight: '800' }, body: { color: colors.muted, fontSize: 13, lineHeight: 19 }, badge: { alignSelf: 'flex-start', color: colors.herb, backgroundColor: colors.herbSoft, paddingHorizontal: 8, paddingVertical: 3, borderRadius: radii.round, fontSize: 11, fontWeight: '700' }, empty: { alignItems: 'center', gap: spacing.md }, emptyTitle: { fontFamily: 'Georgia', fontSize: 24, color: colors.charcoal, fontWeight: '700', textAlign: 'center' } });
