import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Screen } from '@/components/ui';
import { useRecipeStore } from '@/data/recipe-store';
import { colors, radii, spacing } from '@/theme';

export default function CookModeScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const recipe = useRecipeStore().findRecipe(id);
  const [stepIndex, setStepIndex] = useState(0);
  const [ingredientsOpen, setIngredientsOpen] = useState(true);
  const [prepared, setPrepared] = useState<string[]>([]);
  if (!recipe) return <Screen style={styles.center}><Text>Recipe not found.</Text><Button label="Close" onPress={() => router.back()} /></Screen>;
  const complete = stepIndex === recipe.steps.length - 1;
  return <Screen style={styles.screen}>
    <View style={styles.top}><Pressable accessibilityLabel="Exit Cook Mode" onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={25} /></Pressable><Text style={styles.progress}>Step {stepIndex + 1} of {recipe.steps.length}</Text><View style={styles.awake}><Ionicons color={colors.herb} name="hand-left-outline" size={18} /><Text style={styles.awakeText}>Keep screen on</Text></View></View>
    <View accessibilityLabel={`Cooking progress: step ${stepIndex + 1} of ${recipe.steps.length}`} style={styles.progressTrack}><View style={[styles.progressFill, { width: `${((stepIndex + 1) / recipe.steps.length) * 100}%` }]} /></View>
    <View style={styles.content}><Text style={styles.recipe}>{recipe.title}</Text><Pressable accessibilityRole="button" accessibilityState={{ expanded: ingredientsOpen }} onPress={() => setIngredientsOpen((open) => !open)} style={styles.ingredientHeader}><Text style={styles.ingredientTitle}>Ingredients · {prepared.length}/{recipe.ingredients.length} ready</Text><Ionicons color={colors.charcoal} name={ingredientsOpen ? 'chevron-up' : 'chevron-down'} size={20} /></Pressable>{ingredientsOpen ? <View style={styles.ingredients}>{recipe.ingredients.map((ingredient) => { const checked = prepared.includes(ingredient.id); return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked }} key={ingredient.id} onPress={() => setPrepared((items) => checked ? items.filter((item) => item !== ingredient.id) : [...items, ingredient.id])} style={styles.ingredient}><Ionicons color={checked ? colors.herb : colors.muted} name={checked ? 'checkmark-circle' : 'ellipse-outline'} size={22} /><Text style={[styles.ingredientText, checked && styles.ingredientReady]}>{ingredient.quantity ? `${ingredient.quantity} ` : ''}{ingredient.name}</Text></Pressable>; })}</View> : null}<Text accessibilityRole="header" style={styles.stepText}>{recipe.steps[stepIndex]}</Text><View style={styles.art}><Ionicons color={colors.coral} name="restaurant-outline" size={76} /></View></View>
    <View style={styles.controls}><Button label="Previous" variant="secondary" disabled={stepIndex === 0} onPress={() => setStepIndex((current) => Math.max(0, current - 1))} /><View style={styles.controlFlex}><Button label={complete ? 'Finish cooking' : 'Next step'} onPress={() => complete ? router.back() : setStepIndex((current) => current + 1)} /></View></View>
  </Screen>;
}
const styles = StyleSheet.create({ screen: { padding: spacing.lg, gap: spacing.md }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, close: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, progress: { color: colors.charcoal, fontWeight: '800' }, awake: { alignItems: 'center' }, awakeText: { color: colors.herb, fontSize: 10, fontWeight: '700' }, progressTrack: { height: 5, backgroundColor: colors.line, borderRadius: radii.round, overflow: 'hidden' }, progressFill: { height: 5, backgroundColor: colors.coral }, content: { flex: 1, gap: spacing.md, paddingTop: spacing.md }, recipe: { color: colors.muted, fontWeight: '700' }, ingredientHeader: { minHeight: 44, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line }, ingredientTitle: { color: colors.charcoal, fontWeight: '800' }, ingredients: { maxHeight: 180, gap: spacing.xs }, ingredient: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, ingredientText: { flex: 1, color: colors.charcoal, fontSize: 15 }, ingredientReady: { color: colors.muted, textDecorationLine: 'line-through' }, stepText: { color: colors.charcoal, fontFamily: 'Georgia', fontSize: 32, lineHeight: 40, fontWeight: '700' }, art: { flex: 1, minHeight: 120, borderRadius: radii.large, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.herbSoft }, controls: { flexDirection: 'row', gap: spacing.sm }, controlFlex: { flex: 1 }, center: { justifyContent: 'center', padding: spacing.lg, gap: spacing.lg } });
