import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Screen } from '@/components/ui';
import { MotionSlot } from '@/components/animations/MotionSlot';
import { useRecipeStore } from '@/data/recipe-store';
import { colors, radii, spacing } from '@/theme';

type CookTimer = { id: string; label: string; seconds: number; running: boolean };
const formatTimer = (seconds: number) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;

export default function CookModeScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const recipe = useRecipeStore().findRecipe(id);
  const [stepIndex, setStepIndex] = useState(0);
  const [ingredientsOpen, setIngredientsOpen] = useState(true);
  const [prepared, setPrepared] = useState<string[]>([]);
  const [timers, setTimers] = useState<CookTimer[]>([]);
  useEffect(() => {
    if (!timers.some((timer) => timer.running && timer.seconds > 0)) return;
    const interval = setInterval(() => setTimers((current) => current.map((timer) => timer.running && timer.seconds > 0 ? { ...timer, seconds: timer.seconds - 1 } : timer)), 1000);
    return () => clearInterval(interval);
  }, [timers]);
  if (!recipe) return <Screen style={styles.center}><Text>Recipe not found.</Text><Button label="Close" onPress={() => router.back()} /></Screen>;
  const stepCount = Math.max(recipe.steps.length, 1);
  const complete = recipe.steps.length === 0 || stepIndex === recipe.steps.length - 1;
  return <Screen style={styles.screen}>
    <View style={styles.top}><Pressable accessibilityLabel="Exit Cook Mode" onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={25} /></Pressable><Text style={styles.progress}>Step {stepIndex + 1} of {stepCount}</Text><View style={styles.awake}><Ionicons color={colors.herb} name="hand-left-outline" size={18} /><Text style={styles.awakeText}>Hands-free layout</Text></View></View>
    <View accessibilityLabel={`Cooking progress: step ${stepIndex + 1} of ${stepCount}`} style={styles.progressTrack}><View style={[styles.progressFill, { width: `${((stepIndex + 1) / stepCount) * 100}%` }]} /></View>
    <View style={styles.content}><Text style={styles.recipe}>{recipe.title}</Text><Pressable accessibilityRole="button" accessibilityState={{ expanded: ingredientsOpen }} onPress={() => setIngredientsOpen((open) => !open)} style={styles.ingredientHeader}><Text style={styles.ingredientTitle}>Ingredients · {prepared.length}/{recipe.ingredients.length} ready</Text><Ionicons color={colors.charcoal} name={ingredientsOpen ? 'chevron-up' : 'chevron-down'} size={20} /></Pressable>{ingredientsOpen ? <View style={styles.ingredients}>{recipe.ingredients.map((ingredient) => { const checked = prepared.includes(ingredient.id); return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked }} key={ingredient.id} onPress={() => setPrepared((items) => checked ? items.filter((item) => item !== ingredient.id) : [...items, ingredient.id])} style={styles.ingredient}><Ionicons color={checked ? colors.herb : colors.muted} name={checked ? 'checkmark-circle' : 'ellipse-outline'} size={22} /><Text style={[styles.ingredientText, checked && styles.ingredientReady]}>{ingredient.quantity ? `${ingredient.quantity} ` : ''}{ingredient.name}</Text></Pressable>; })}</View> : null}<Text accessibilityRole="header" style={styles.stepText}>{recipe.steps[stepIndex] ?? 'No directions have been added to this recipe yet.'}</Text><View style={styles.art}><MotionSlot name='onboarding-recipe-card' size={100} accessibilityLabel='Gentle cooking motion' /><Ionicons color={colors.coral} name="restaurant-outline" size={44} /></View></View>
    <View style={styles.timerPanel}><View style={styles.timerHeader}><Text style={styles.ingredientTitle}>Step timers</Text><View style={styles.quickTimers}>{[1, 5, 10].map((minutes) => <Pressable accessibilityLabel={`Start ${minutes} minute timer for step ${stepIndex + 1}`} key={minutes} onPress={() => setTimers((current) => [...current, { id: `${Date.now()}_${minutes}`, label: `Step ${stepIndex + 1}`, seconds: minutes * 60, running: true }])} style={styles.quickTimer}><Text style={styles.quickTimerText}>+{minutes}m</Text></Pressable>)}</View></View>{timers.length ? timers.map((timer) => <View accessibilityLiveRegion="polite" key={timer.id} style={[styles.timer, timer.seconds === 0 && styles.timerDone]}><View style={styles.timerIdentity}><Text style={styles.timerLabel}>{timer.label}</Text><Text style={styles.timerTime}>{timer.seconds === 0 ? 'Done' : formatTimer(timer.seconds)}</Text></View><Pressable accessibilityLabel={timer.running ? `Pause ${timer.label} timer` : `Resume ${timer.label} timer`} disabled={timer.seconds === 0} onPress={() => setTimers((current) => current.map((item) => item.id === timer.id ? { ...item, running: !item.running } : item))} style={styles.timerAction}><Ionicons color={colors.charcoal} name={timer.running ? 'pause' : 'play'} size={18} /></Pressable><Pressable accessibilityLabel={`Add one minute to ${timer.label} timer`} onPress={() => setTimers((current) => current.map((item) => item.id === timer.id ? { ...item, seconds: item.seconds + 60, running: true } : item))} style={styles.timerAction}><Text style={styles.timerActionText}>+1</Text></Pressable><Pressable accessibilityLabel={`Remove ${timer.label} timer`} onPress={() => setTimers((current) => current.filter((item) => item.id !== timer.id))} style={styles.timerAction}><Ionicons color={colors.muted} name="close" size={18} /></Pressable></View>) : <Text style={styles.timerHint}>Start a labeled timer without leaving this step.</Text>}</View>
    <View style={styles.controls}><Button label="Previous" variant="secondary" disabled={stepIndex === 0} onPress={() => setStepIndex((current) => Math.max(0, current - 1))} /><View style={styles.controlFlex}><Button label={complete ? 'Finish cooking' : 'Next step'} onPress={() => complete ? router.replace(`/cook/${recipe.id}/finished`) : setStepIndex((current) => current + 1)} /></View></View>
  </Screen>;
}
const styles = StyleSheet.create({ screen: { padding: spacing.lg, gap: spacing.md }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, close: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, progress: { color: colors.charcoal, fontWeight: '800' }, awake: { alignItems: 'center' }, awakeText: { color: colors.herb, fontSize: 10, fontWeight: '700' }, progressTrack: { height: 5, backgroundColor: colors.line, borderRadius: radii.round, overflow: 'hidden' }, progressFill: { height: 5, backgroundColor: colors.coral }, content: { flex: 1, gap: spacing.md, paddingTop: spacing.md }, recipe: { color: colors.muted, fontWeight: '700' }, ingredientHeader: { minHeight: 44, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line }, ingredientTitle: { color: colors.charcoal, fontWeight: '800' }, ingredients: { maxHeight: 180, gap: spacing.xs }, ingredient: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, ingredientText: { flex: 1, color: colors.charcoal, fontSize: 15 }, ingredientReady: { color: colors.muted, textDecorationLine: 'line-through' }, stepText: { color: colors.charcoal, fontFamily: 'System', fontSize: 30, lineHeight: 37, fontWeight: '700' }, art: { flex: 1, minHeight: 80, borderRadius: radii.large, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.mintSoft }, timerPanel: { gap: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radii.medium, padding: spacing.sm, backgroundColor: colors.paperRaised }, timerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm }, quickTimers: { flexDirection: 'row', gap: spacing.xs }, quickTimer: { minWidth: 44, minHeight: 36, alignItems: 'center', justifyContent: 'center', borderRadius: radii.round, backgroundColor: colors.lemonSoft }, quickTimerText: { color: colors.charcoal, fontWeight: '800' }, timer: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: spacing.xs, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: spacing.xs }, timerDone: { backgroundColor: colors.herbSoft }, timerIdentity: { flex: 1 }, timerLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' }, timerTime: { color: colors.charcoal, fontSize: 20, fontWeight: '900', fontVariant: ['tabular-nums'] }, timerAction: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, borderWidth: 1, borderColor: colors.line }, timerActionText: { color: colors.charcoal, fontWeight: '900' }, timerHint: { color: colors.muted, fontSize: 13 }, controls: { flexDirection: 'row', gap: spacing.sm }, controlFlex: { flex: 1 }, center: { justifyContent: 'center', padding: spacing.lg, gap: spacing.lg } });
