import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Screen, Title } from '@/components/ui';
import { colors, radii, spacing, typography } from '@/theme';

const initialPosts = [
  { id: '1', name: 'Samira J.', title: 'Creamy Tomato Burrata Pasta', caption: 'Made this for a weeknight dinner and it was a total keeper.', time: '12 min · Easy', likes: 48, comments: 6, color: colors.coral, soft: '#FFF0ED', icon: 'restaurant-outline' },
  { id: '2', name: 'Alex R.', title: 'Hot Honey Salmon Bowl', caption: 'The sweet heat on this one is perfect with avocado and rice.', time: '30 min · High protein', likes: 32, comments: 4, color: colors.lemon, soft: colors.lemonSoft, icon: 'flame-outline' },
  { id: '3', name: 'Taylor J.', title: 'Green Goddess Salad', caption: 'Fresh, crunchy, and ready before the rest of dinner.', time: '15 min · Quick', likes: 27, comments: 3, color: colors.herb, soft: colors.herbSoft, icon: 'leaf-outline' },
];

const POSTS_KEY = 'cravekeep.community.posts.v1';

export default function CommunityScreen() {
  const [posts, setPosts] = useState(initialPosts);
  const [liked, setLiked] = useState<string[]>([]);
  const [saved, setSaved] = useState<string[]>([]);
  useEffect(() => { void AsyncStorage.getItem(POSTS_KEY).then((value) => { if (!value) return; try { const stored = JSON.parse(value); if (Array.isArray(stored)) setPosts([...stored, ...initialPosts]); } catch { /* ignore malformed local data */ } }); }, []);
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>COMMUNITY</Text><Title>See what cooks are keeping.</Title></View><View style={styles.icon}><Ionicons color={colors.white} name="people-outline" size={24} /></View></View>
    <View style={styles.tabs}><Text style={styles.tabActive}>For you</Text><Pressable onPress={() => router.push('/discover')}><Text style={styles.tab}>Discover</Text></Pressable><Text style={styles.tab}>Following</Text></View>
    {posts.map((post) => { const isLiked = liked.includes(post.id); const isSaved = saved.includes(post.id); return <Card key={post.id} style={styles.post}><View style={styles.postHeader}><View style={styles.avatar}><Text style={styles.avatarText}>{post.name.slice(0, 1)}</Text></View><View style={styles.flex}><Text style={styles.name}>{post.name}</Text><Text style={styles.time}>Shared a recipe · {post.time}</Text></View><Ionicons color={colors.muted} name="ellipsis-horizontal" size={20} /></View><Pressable accessibilityRole="button" onPress={() => router.push('/(tabs)/recipes')} style={[styles.art, { backgroundColor: post.soft }]}><Ionicons color={post.color} name={post.icon as keyof typeof Ionicons.glyphMap} size={55} /></Pressable><Text style={styles.recipeTitle}>{post.title}</Text><Text style={styles.caption}>{post.caption}</Text><View style={styles.actions}><Pressable accessibilityLabel={isLiked ? 'Unlike recipe' : 'Like recipe'} onPress={() => setLiked((current) => isLiked ? current.filter((id) => id !== post.id) : [...current, post.id])} style={styles.action}><Ionicons color={isLiked ? colors.coral : colors.muted} name={isLiked ? 'heart' : 'heart-outline'} size={21} /><Text style={styles.actionText}>{post.likes + (isLiked ? 1 : 0)}</Text></Pressable><View style={styles.action}><Ionicons color={colors.muted} name="chatbubble-outline" size={20} /><Text style={styles.actionText}>{post.comments}</Text></View><Pressable accessibilityLabel={isSaved ? 'Remove saved recipe' : 'Save recipe'} onPress={() => setSaved((current) => isSaved ? current.filter((id) => id !== post.id) : [...current, post.id])} style={styles.save}><Ionicons color={isSaved ? colors.coral : colors.muted} name={isSaved ? 'bookmark' : 'bookmark-outline'} size={21} /><Text style={styles.actionText}>{isSaved ? 'Saved' : 'Save'}</Text></Pressable></View></Card>; })}
    <Card style={styles.share}><Ionicons color={colors.herb} name="add-circle-outline" size={28} /><View style={styles.flex}><Text style={styles.recipeTitle}>Share something from your kitchen.</Text><Text style={styles.caption}>Create a recipe or capture one to add it to your community.</Text></View><Pressable accessibilityLabel="Open Capture Studio" onPress={() => router.push('/community/share')}><Ionicons color={colors.coral} name="arrow-forward-circle" size={28} /></Pressable></Card>
  </ScrollView></Screen>;
}

const styles=StyleSheet.create({content:{padding:spacing.lg,gap:spacing.md,paddingBottom:110},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},eyebrow:{color:colors.coralDark,...typography.label,letterSpacing:1.1},icon:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:colors.coral},tabs:{flexDirection:'row',gap:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:spacing.sm},tab:{color:colors.muted,fontWeight:'800'},tabActive:{color:colors.coral,fontWeight:'900'},post:{gap:spacing.sm},postHeader:{flexDirection:'row',alignItems:'center',gap:spacing.sm},avatar:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:colors.charcoal},avatarText:{color:colors.white,fontWeight:'900'},flex:{flex:1,gap:3},name:{color:colors.charcoal,fontWeight:'900'},time:{color:colors.muted,fontSize:12},art:{height:150,borderRadius:radii.medium,alignItems:'center',justifyContent:'center'},recipeTitle:{color:colors.charcoal,fontSize:17,fontWeight:'900'},caption:{color:colors.muted,lineHeight:20},actions:{flexDirection:'row',alignItems:'center',gap:spacing.lg,paddingTop:spacing.xs},action:{flexDirection:'row',alignItems:'center',gap:5},actionText:{color:colors.muted,fontWeight:'800'},save:{marginLeft:'auto',flexDirection:'row',alignItems:'center',gap:5},share:{flexDirection:'row',alignItems:'center',gap:spacing.md,backgroundColor:colors.herbSoft}});
