import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Screen, Title } from '@/components/ui';
import { MotionSlot } from '@/components/animations/MotionSlot';
import { useImportStore } from '@/data/import-store';
import { colors, radii, spacing } from '@/theme';

const statusLabel = { queued: 'Queued', processing: 'Processing', needs_review: 'Needs review', completed: 'Completed', failed: 'Needs attention' } as const;

export default function ImportsScreen() {
  const { jobs, ready, error } = useImportStore();
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={24} /></Pressable><Button label="New import" variant="quiet" onPress={() => router.push('/capture')} /></View><MotionSlot name="recipe-import-success" size={88} accessibilityLabel="Animated recipe import status" /><Title>Imports</Title><Text style={styles.body}>Active, completed, and needs-review recipes stay here with their source and recovery path.</Text>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{!ready ? <ActivityIndicator color={colors.coral} /> : jobs.length === 0 ? <Card style={styles.empty}><Ionicons color={colors.coral} name="file-tray-outline" size={54} /><Text style={styles.jobTitle}>No imports yet</Text><Text style={styles.body}>Paste your first recipe link to begin.</Text><Button label="Paste a link" onPress={() => router.push('/capture/link')} /></Card> : jobs.map((job) => {
      const action = job.recipeId ? 'Open recipe' : job.status === 'needs_review' ? 'Review recipe' : job.status === 'failed' ? 'Retry import' : job.status === 'processing' ? 'Resume import' : job.status === 'queued' ? 'Start import' : 'Open import';
      return <Pressable accessibilityLabel={`${job.source.title}, ${statusLabel[job.status]}. ${action}.`} accessibilityRole="button" key={job.id} onPress={() => job.status === 'needs_review' ? router.push({ pathname: '/capture/review', params: { jobId: job.id } }) : job.recipeId ? router.push(`/recipes/${job.recipeId}`) : job.status === 'failed' || job.status === 'processing' || job.status === 'queued' ? router.push({ pathname: '/capture/processing', params: { jobId: job.id } }) : undefined}><Card style={styles.job}><View style={styles.row}>{job.source.localUri || job.source.imageUrl ? <Image accessibilityLabel="Import reference" source={{ uri: job.source.localUri ?? job.source.imageUrl }} style={styles.preview} /> : <View style={[styles.icon, job.status === 'needs_review' && styles.iconWarning, job.status === 'failed' && styles.iconError]}><Ionicons color={job.recipeId ? colors.mint : colors.coral} name={job.recipeId ? 'checkmark' : job.status === 'needs_review' ? 'alert' : job.status === 'failed' ? 'refresh' : 'hourglass-outline'} size={23} /></View>}<View style={styles.copy}><Text style={styles.jobTitle}>{job.source.title}</Text><Text style={styles.host}>{job.source.platform ? `${job.source.platform[0].toUpperCase() + job.source.platform.slice(1)} · ` : ''}{job.source.host}</Text><Text style={[styles.status, job.status === 'needs_review' && styles.statusWarning, job.status === 'failed' && styles.statusError]}>{statusLabel[job.status]} · {action}</Text><Text style={styles.updated}>Updated {new Date(job.updatedAt).toLocaleDateString()}</Text>{job.warnings[0] ? <Text numberOfLines={2} style={styles.warningText}>{job.warnings[0]}</Text> : null}</View><Ionicons color={colors.muted} name="chevron-forward" size={22} /></View></Card></Pressable>;
    })}
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.md, paddingBottom: 60 }, header: { flexDirection: 'row', justifyContent: 'space-between' }, back: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, body: { color: colors.muted, lineHeight: 21 }, empty: { alignItems: 'center', gap: spacing.md }, job: { gap: spacing.sm }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, preview: { width: 46, height: 46, borderRadius: radii.medium, resizeMode: 'cover' }, icon: { width: 46, height: 46, borderRadius: radii.medium, backgroundColor: colors.mintSoft, alignItems: 'center', justifyContent: 'center' }, iconWarning: { backgroundColor: colors.lemonSoft }, iconError: { backgroundColor: '#FFF0ED' }, copy: { flex: 1, gap: 3 }, jobTitle: { color: colors.charcoal, fontSize: 17, fontWeight: '800' }, host: { color: colors.muted }, status: { color: colors.mint, fontSize: 12, fontWeight: '800' }, statusWarning: { color: colors.coralDark }, statusError: { color: colors.coralDark }, updated: { color: colors.muted, fontSize: 11 }, warningText: { color: colors.charcoal, fontSize: 12, lineHeight: 17, marginTop: spacing.xs }, error: { color: colors.coralDark, backgroundColor: '#FFF0ED', padding: spacing.md, borderRadius: radii.medium } });
