import type { PantryConfidence } from '@cravekeep/domain';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MotionSlot } from '@/components/animations/MotionSlot';
import { Button, Card, Eyebrow, Field, Screen, SectionTitle, Title } from '@/components/ui';
import { usePantryStore } from '@/data/pantry-store';
import { useRecipeStore } from '@/data/recipe-store';
import { colors, radii, spacing } from '@/theme';
const confidences: PantryConfidence[] = ['confirmed', 'estimated', 'unknown'];
export default function PantryScreen() { const { items, ready, saveItem, removeItem, error } = usePantryStore(); const { recipes } = useRecipeStore(); const [name, setName] = useState(''); const [quantity, setQuantity] = useState(''); const [expiresOn, setExpiresOn] = useState(''); const [confidence, setConfidence] = useState<PantryConfidence>('unknown'); const [message, setMessage] = useState<string>();
  const today = new Date().toISOString().slice(0, 10); const soon = new Date(); soon.setDate(soon.getDate() + 7); const soonDate = soon.toISOString().slice(0, 10); const useSoonKeys = new Set(items.filter((item) => item.expiresOn && item.expiresOn >= today && item.expiresOn <= soonDate).map((item) => item.key));
  const suggested = useMemo(() => recipes.filter((recipe) => recipe.ingredients.some((ingredient) => useSoonKeys.has(ingredient.name.trim().toLowerCase().replace(/\s+/g, ' ')))).slice(0, 5), [recipes, useSoonKeys]);
  const save = async () => { const key = name.trim().toLowerCase().replace(/\s+/g, ' '); if (!key) { setMessage('Enter a pantry item name.'); return; } if (expiresOn && !/^\d{4}-\d{2}-\d{2}$/.test(expiresOn)) { setMessage('Use YYYY-MM-DD for the expiration date.'); return; } await saveItem({ key, name: name.trim(), quantity: quantity.trim(), confidence, expiresOn: expiresOn || undefined, updatedAt: new Date().toISOString() }); setName(''); setQuantity(''); setExpiresOn(''); setConfidence('unknown'); setMessage('Pantry item saved.'); };
  return <Screen><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={24} /></Pressable></View><MotionSlot name="grocery-progress" size={80} accessibilityLabel="Animated pantry inventory" /><ActivityIndicator animating={!ready} color={colors.coral} accessibilityLabel={ready ? undefined : 'Loading pantry'} /><Eyebrow>PANTRY</Eyebrow><Title>Know what you have—with confidence.</Title><Text style={styles.body}>Quantities are labeled confirmed, estimated, or unknown. CraveKeep does not subtract uncertain stock from groceries as if it were exact.</Text>
    <Card style={styles.form}><SectionTitle>Add or update</SectionTitle><Field label="Item" value={name} onChangeText={setName} /><Field label="Quantity" value={quantity} onChangeText={setQuantity} /><Field autoCapitalize="none" label="Expiration (YYYY-MM-DD, optional)" value={expiresOn} onChangeText={setExpiresOn} /><View style={styles.options}>{confidences.map((item) => <Pressable accessibilityRole="button" accessibilityState={{ selected: confidence === item }} key={item} onPress={() => setConfidence(item)} style={[styles.option, confidence === item && styles.optionActive]}><Text style={[styles.optionText, confidence === item && styles.optionTextActive]}>{item}</Text></Pressable>)}</View><Button label="Save pantry item" onPress={() => void save()} /></Card>
    <SectionTitle>Inventory</SectionTitle>{items.length ? items.map((item) => <Card key={item.key} style={styles.item}><View style={styles.flex}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.meta}>{item.quantity || 'Quantity not recorded'} · {item.confidence}</Text>{item.expiresOn ? <Text style={item.expiresOn <= soonDate ? styles.soon : styles.meta}>Expires {item.expiresOn}</Text> : null}</View><Pressable accessibilityLabel={`Remove ${item.name}`} onPress={() => void removeItem(item.key)}><Ionicons color={colors.coralDark} name="trash-outline" size={20} /></Pressable></Card>) : <Text style={styles.body}>No pantry items yet.</Text>}
    <SectionTitle>Use soon</SectionTitle>{suggested.length ? suggested.map((recipe) => <Pressable accessibilityRole="button" key={recipe.id} onPress={() => router.push(`/recipes/${recipe.id}`)} style={styles.recipe}><Ionicons color={colors.herb} name="leaf" size={22} /><Text style={styles.itemName}>{recipe.title}</Text></Pressable>) : <Text style={styles.body}>Add an expiration date within the next seven days to see matching recipes.</Text>}{message || error ? <Text accessibilityRole="alert" style={styles.message}>{message ?? error}</Text> : null}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.md, paddingBottom: 80 }, header: { flexDirection: 'row' }, back: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.paperRaised, alignItems: 'center', justifyContent: 'center' }, body: { color: colors.muted, lineHeight: 22 }, form: { gap: spacing.sm }, options: { flexDirection: 'row', gap: spacing.sm }, option: { flex: 1, alignItems: 'center', padding: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radii.round }, optionActive: { backgroundColor: colors.coral, borderColor: colors.coral }, optionText: { color: colors.charcoal, fontWeight: '800', textTransform: 'capitalize' }, optionTextActive: { color: colors.white }, item: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, flex: { flex: 1 }, itemName: { color: colors.charcoal, fontWeight: '900' }, meta: { color: colors.muted, textTransform: 'capitalize' }, soon: { color: colors.coralDark, fontWeight: '800' }, recipe: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radii.medium, backgroundColor: colors.herbSoft }, message: { color: colors.coralDark, fontWeight: '700' } });
