import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { OnboardingShell, Panel } from '@/components/onboarding-shell';
import { Button, Field } from '@/components/ui';
import { useAuthStore } from '@/data/auth-store';
import { colors, spacing, typography } from '@/theme';

export default function EmailAccountScreen() {
  const { mode } = useLocalSearchParams<{ mode?: string }>();
  const signingIn = mode === 'signin'; const resetting = mode === 'reset';
  const { resetPassword, resendVerification, signIn, signUp, updatePassword } = useAuthStore();
  const [verificationSent, setVerificationSent] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>(); const [resetSent, setResetSent] = useState(false);
  const validEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
  const rules = [{ met: password.length >= 8, label: 'At least 8 characters' }, { met: /[a-z]/.test(password), label: 'One lowercase letter' }, { met: /[A-Z]/.test(password), label: 'One uppercase letter' }, { met: /[^A-Za-z]/.test(password), label: 'One number or symbol' }];
  const resend = async () => { if (!validEmail) { setMessage('Enter a valid email address first.'); return; } setBusy(true); setMessage(undefined); try { const result = await resendVerification(email); if (result.error) setMessage(result.error); else setVerificationSent(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not resend the verification email.'); } finally { setBusy(false); } };
  const saveNewPassword = async () => { if (!rules.every(rule => rule.met)) { setMessage('Choose a password that meets all requirements.'); return; } setBusy(true); setMessage(undefined); try { const result = await updatePassword(password); if (result.error) setMessage(result.error); else setResetSent(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not update your password.'); } finally { setBusy(false); } };
  const sendReset = async () => { if (!validEmail) { setMessage('Enter a valid email address so we know where to send the reset link.'); return; } setBusy(true); setMessage(undefined); try { const result = await resetPassword(email); if (result.error) setMessage(result.error); else setResetSent(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not send the reset email.'); } finally { setBusy(false); } };
  const submit = async () => { if (!validEmail || (signingIn ? !password : !rules.every(rule => rule.met) || !name.trim())) { setMessage(signingIn ? 'Enter a valid email and password.' : 'Complete the required fields and password rules.'); return; } setBusy(true); setMessage(undefined); try { const result = signingIn ? await signIn(email, password) : await signUp(email, password, name); if (result.error) setMessage(result.error); else if (result.confirmationRequired) setMessage('Check your email to verify your account, then return to sign in.'); else router.replace('/'); } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not complete that request.'); } finally { setBusy(false); } };
  const title = resetting ? 'Reset your password' : signingIn ? 'Welcome back' : 'Create your account';
  const percent = resetting ? 80 : signingIn ? 20 : 35;
  return <OnboardingShell title={title} percent={percent} footer={<Button disabled={busy} label={resetSent && resetting ? 'Continue to sign in' : busy ? 'Connecting…' : resetting ? 'Save new password' : signingIn ? 'Sign in' : 'Create account'} onPress={() => void (resetSent && resetting ? router.replace('/onboarding/email?mode=signin') : resetting ? saveNewPassword() : submit())} />}>
    <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.flex}>
      <View style={styles.hero}><View style={styles.icon}><Ionicons color={colors.white} name={resetting ? 'key-outline' : signingIn ? 'log-in-outline' : 'mail-outline'} size={30} /></View><Text style={styles.heroTitle}>{resetting ? 'Secure account access' : signingIn ? 'Your kitchen is waiting.' : 'A private home for every recipe.'}</Text><Text style={styles.heroBody}>{resetting ? 'Choose a new password and get back to cooking.' : signingIn ? 'Sign in to find every recipe, plan, and grocery list in one place.' : 'Create your CraveKeep account and keep your recipes synced across devices.'}</Text></View>
      <Panel><View style={styles.form}>{!signingIn && !resetting ? <Field autoComplete="name" label="First name" onChangeText={setName} placeholder="Jason" value={name} /> : null}{!resetting ? <Field autoCapitalize="none" autoComplete="email" keyboardType="email-address" label="Email" onChangeText={setEmail} placeholder="you@example.com" value={email} /> : null}<Field autoCapitalize="none" autoComplete={signingIn ? 'current-password' : 'new-password'} label="Password" onChangeText={setPassword} placeholder="Create a secure password" secureTextEntry value={password} />{!signingIn || resetting ? <View style={styles.rules}>{rules.map(rule => <Text key={rule.label} style={rule.met ? styles.ruleMet : styles.rule}><Ionicons color={rule.met ? colors.herb : colors.muted} name={rule.met ? 'checkmark-circle' : 'ellipse-outline'} /> {rule.label}</Text>)}</View> : null}</View></Panel>
      {resetSent ? <Text accessibilityRole="status" style={styles.success}>{resetting ? 'Your password has been updated. You can now sign in.' : 'Check your email for a secure password-reset link.'}</Text> : null}{verificationSent ? <Text accessibilityRole="status" style={styles.success}>A new verification email has been sent.</Text> : null}{message ? <Text accessibilityRole="alert" style={styles.message}>{message}</Text> : null}
      {signingIn ? <Pressable disabled={busy} onPress={() => void sendReset()}><Text style={styles.link}>Forgot your password?</Text></Pressable> : null}{!signingIn && !resetting ? <Pressable disabled={busy} onPress={() => void resend()}><Text style={styles.link}>Resend verification email</Text></Pressable> : null}
      <Pressable onPress={() => router.replace('/onboarding/account')}><Text style={styles.alt}>Use another sign-in method</Text></Pressable>
    </KeyboardAvoidingView>
  </OnboardingShell>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, hero: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.sm }, icon: { width: 66, height: 66, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.coral }, heroTitle: { color: colors.charcoal, ...typography.title, fontSize: 23, textAlign: 'center' }, heroBody: { color: colors.muted, lineHeight: 20, textAlign: 'center' }, form: { gap: spacing.md, padding: spacing.md }, rules: { gap: spacing.sm, paddingTop: spacing.xs }, rule: { color: colors.muted, fontSize: 13 }, ruleMet: { color: colors.herb, ...typography.label, fontSize: 13 }, link: { color: colors.coralDark, textAlign: 'center', ...typography.label }, alt: { color: colors.muted, textAlign: 'center', fontSize: 13, paddingVertical: spacing.sm }, message: { color: colors.coralDark, textAlign: 'center', lineHeight: 20 }, success: { color: colors.herb, textAlign: 'center', fontWeight: '800', lineHeight: 20 } });