import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { OnboardingShell } from '@/components/onboarding-shell';
import { MotionSlot } from '@/components/animations/MotionSlot';
import { Button, Field } from '@/components/ui';
import { useOnboardingStore } from '@/data/onboarding-store';
import { colors, radii, spacing, typography } from '@/theme';

type Draft = { name: string; type: 'adult'|'child'; allergies: string; preferences: string };
const empty: Draft = { name:'', type:'adult', allergies:'', preferences:'' };
export default function HouseholdScreen(){
  const {profile,update,saveHousehold,saving,error}=useOnboardingStore(); const [adding,setAdding]=useState(false); const [draft,setDraft]=useState(empty); const [message,setMessage]=useState<string>();
  const add=()=>{if(!draft.name.trim()){setMessage('Enter the household member’s name.');return;}void update({householdMembers:[...profile.householdMembers,{id:`local-${Date.now()}`,name:draft.name.trim(),type:draft.type,allergies:draft.allergies.split(',').map(x=>x.trim()).filter(Boolean),preferences:draft.preferences.split(',').map(x=>x.trim()).filter(Boolean)}]});setDraft(empty);setAdding(false);setMessage(undefined)};
  const next=async()=>{if(!profile.householdName.trim()){setMessage('Name your household or choose continue solo.');return;}if(!await saveHousehold())router.push('/onboarding/settings')};
  const solo=async()=>{await update({householdName:`${profile.displayName||'My'}’s Kitchen`,householdMembers:[]});if(!await saveHousehold())router.push('/onboarding/settings')};
  return <OnboardingShell title="Your household" percent={92} footer={<View style={styles.footer}><Button disabled={saving} label={saving?'Saving…':'Save household'} onPress={()=>void next()}/><Button disabled={saving} label="Continue solo" variant="quiet" onPress={()=>void solo()}/></View>}>
    <View style={styles.heroBlock}><MotionSlot name="onboarding-preferences" size={76} accessibilityLabel="Animated household preferences" /><View style={styles.heroCopy}><Text style={styles.hero}>Plan once. Serve everyone.</Text><Text style={styles.body}>Household members can have their own preferences, allergies, and portions. This step is optional.</Text></View></View>
    <View style={styles.houseCard}><View style={styles.houseIcon}><Ionicons color={colors.herb} name="home" size={28}/></View><View style={styles.flex}><Field label="Household name" onChangeText={householdName=>void update({householdName})} placeholder="The Sampson Kitchen" value={profile.householdName}/></View></View>
    <View><Text style={styles.section}>Members</Text><View style={styles.list}><View style={styles.member}><View style={styles.avatar}><Text style={styles.initial}>{(profile.displayName||'Y').slice(0,1).toUpperCase()}</Text></View><View style={styles.flex}><Text style={styles.memberName}>{profile.displayName||'You'} <Text style={styles.you}>(You)</Text></Text><Text style={styles.small}>Uses your private food and nutrition profile</Text></View><Text style={styles.role}>Owner</Text></View>{profile.householdMembers.map(member=><View key={member.id} style={styles.member}><View style={[styles.avatar,member.type==='child'&&styles.child]}><Text style={styles.initial}>{member.name.slice(0,1).toUpperCase()}</Text></View><View style={styles.flex}><Text style={styles.memberName}>{member.name}</Text><Text numberOfLines={1} style={styles.small}>{member.preferences.length?`Likes: ${member.preferences.join(', ')}`:'No food preferences yet'}</Text>{member.allergies.length?<Text style={styles.allergy}>Allergy: {member.allergies.join(', ')}</Text>:null}</View><Pressable accessibilityLabel={`Remove ${member.name}`} onPress={()=>void update({householdMembers:profile.householdMembers.filter(value=>value.id!==member.id)})}><Ionicons color={colors.muted} name="close-circle-outline" size={23}/></Pressable></View>)}</View></View>
    {adding?<View style={styles.form}><Text style={styles.section}>Add a household member</Text><Field autoCapitalize="words" label="Name" onChangeText={name=>setDraft(current=>({...current,name}))} value={draft.name}/><Text style={styles.label}>Member type</Text><View style={styles.options}>{(['adult','child'] as const).map(type=><Pressable key={type} onPress={()=>setDraft(current=>({...current,type}))} style={[styles.option,draft.type===type&&styles.optionActive]}><Text style={[styles.optionText,draft.type===type&&styles.optionTextActive]}>{type==='adult'?'Adult':'Child'}</Text></Pressable>)}</View><Field label="Allergies (comma separated)" onChangeText={allergies=>setDraft(current=>({...current,allergies}))} placeholder="Peanuts, dairy" value={draft.allergies}/><Field label="Foods they like (comma separated)" onChangeText={preferences=>setDraft(current=>({...current,preferences}))} placeholder="Pasta, chicken, broccoli" value={draft.preferences}/><View style={styles.formButtons}><View style={styles.flex}><Button label="Cancel" variant="quiet" onPress={()=>setAdding(false)}/></View><View style={styles.flex}><Button label="Add member" onPress={add}/></View></View></View>:<Pressable onPress={()=>setAdding(true)} style={styles.add}><Ionicons color={colors.coralDark} name="add-circle-outline" size={23}/><View style={styles.flex}><Text style={styles.addTitle}>Add someone in your household</Text><Text style={styles.small}>Set up their needs without creating an account</Text></View></Pressable>}
    <View><Text style={styles.section}>Shared together</Text><View style={styles.controls}>{[['book-outline','Recipes'],['calendar-outline','Meal plans'],['basket-outline','Groceries']].map(([icon,label])=><View key={label} style={styles.control}><Ionicons color={colors.herb} name={icon as keyof typeof Ionicons.glyphMap} size={25}/><Text style={styles.controlText}>{label}</Text></View>)}</View></View>
    <View style={styles.notice}><Ionicons color={colors.herb} name="shield-checkmark-outline" size={24}/><Text style={styles.noticeText}>Health details remain private. Sharing controls can be changed later in Household settings.</Text></View>{message||error?<Text accessibilityRole="alert" style={styles.error}>{message||error}</Text>:null}
  </OnboardingShell>;
}
const styles=StyleSheet.create({footer:{gap:4},heroBlock:{flexDirection:'row',alignItems:'center',gap:spacing.sm},heroCopy:{flex:1},hero:{...typography.title,fontSize:25,color:colors.charcoal},body:{color:colors.muted,lineHeight:20},houseCard:{flexDirection:'row',alignItems:'center',gap:12,padding:12,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,backgroundColor:colors.paperRaised},houseIcon:{width:52,height:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:colors.mintSoft},flex:{flex:1},section:{marginBottom:spacing.sm,...typography.label,fontSize:16,color:colors.charcoal},list:{overflow:'hidden',borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,backgroundColor:colors.paperRaised},member:{minHeight:74,padding:11,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},avatar:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:colors.charcoal},child:{backgroundColor:colors.herb},initial:{color:colors.white,fontWeight:'900'},memberName:{fontWeight:'800'},you:{color:colors.muted,fontWeight:'500'},small:{color:colors.muted,fontSize:11,lineHeight:16},allergy:{color:colors.coralDark,fontSize:11,fontWeight:'800'},role:{padding:6,borderRadius:radii.round,backgroundColor:colors.herbSoft,color:colors.mint,fontSize:10},add:{flexDirection:'row',alignItems:'center',gap:10,padding:14,borderWidth:1,borderStyle:'dashed',borderColor:colors.coral,borderRadius:radii.medium},addTitle:{fontWeight:'800',color:colors.coralDark},form:{padding:spacing.md,gap:spacing.md,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,backgroundColor:colors.paperRaised},label:{fontWeight:'700',color:colors.charcoal},options:{flexDirection:'row',gap:8},option:{flex:1,minHeight:43,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line,borderRadius:radii.small},optionActive:{backgroundColor:colors.charcoal},optionText:{fontWeight:'700'},optionTextActive:{color:colors.white},formButtons:{flexDirection:'row',gap:8},controls:{flexDirection:'row',gap:8},control:{flex:1,alignItems:'center',padding:12,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium},controlText:{marginTop:4,fontWeight:'700',fontSize:11},notice:{flexDirection:'row',gap:10,padding:12,borderWidth:1,borderColor:colors.lemon,borderRadius:radii.medium},noticeText:{flex:1,color:colors.muted,fontSize:11,lineHeight:16},error:{color:colors.coralDark,textAlign:'center'}});
