import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { OnboardingShell } from '@/components/onboarding-shell';
import { Button, Field } from '@/components/ui';
import { useOnboardingStore } from '@/data/onboarding-store';
import { colors, radii, spacing, typography } from '@/theme';

const goals = [['balanced','Eat more balanced'],['lose','Lose weight'],['maintain','Maintain weight'],['gain','Gain weight'],['muscle','Build muscle'],['none','No nutrition target']] as const;
const activities = [['sedentary','Mostly seated'],['light','Lightly active'],['moderate','Moderately active'],['active','Very active']] as const;
const activityFactors: Record<string,number> = { sedentary: 1.2, light: 1.375, moderate: 1.55, active: 1.725 };
const numberValue = (value: string) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : undefined; };

export default function NutritionGoalsScreen() {
  const { profile, update, saveNutritionGoals, saving, error } = useOnboardingStore(); const [message,setMessage]=useState<string>();
  const calculate = async () => {
    if (!profile.age || !profile.heightCm || !profile.currentWeightKg || !profile.sexForCalculation || !profile.activityLevel) { setMessage('Complete age, calculation sex, height, current weight, and activity level.'); return; }
    const base = 10 * profile.currentWeightKg + 6.25 * profile.heightCm - 5 * profile.age + (profile.sexForCalculation === 'male' ? 5 : -161);
    const adjustment = profile.goal === 'lose' ? -400 : profile.goal === 'gain' || profile.goal === 'muscle' ? 300 : 0;
    const calories = Math.max(1200, Math.round((base * activityFactors[profile.activityLevel] + adjustment) / 10) * 10);
    const protein = Math.round(profile.currentWeightKg * (profile.goal === 'muscle' || profile.goal === 'lose' ? 1.8 : 1.4));
    const fat = Math.round(calories * 0.28 / 9); const carbs = Math.max(0, Math.round((calories - protein * 4 - fat * 9) / 4));
    await update({ calculationMode:'calculated', calories, protein:`${protein} g`, carbs:`${carbs} g`, fat:`${fat} g`, fiber:`${Math.max(25,Math.round(calories/1000*14))} g` }); setMessage('Estimate calculated. Review and adjust it before saving.');
  };
  const next = async () => { setMessage('Saving your nutrition goals…'); try { if (!await saveNutritionGoals()) router.push('/onboarding/settings'); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'We could not save your nutrition goals. Please try again.'); } };
  return <OnboardingShell title="Nutrition direction" percent={80} footer={<Button disabled={saving} label={saving?'Saving…':'Save and continue'} onPress={()=>void next()} />}>
    <View><Text style={styles.hero}>What would you like meals to support?</Text><Text style={styles.body}>This guides recipe portions and suggestions. CraveKeep is not medical advice or a required food tracker.</Text></View>
    <View style={styles.goalGrid}>{goals.map(([value,label])=><Pressable key={value} onPress={()=>void update({goal:value})} style={[styles.goal,profile.goal===value&&styles.selected]}><Text style={[styles.goalText,profile.goal===value&&styles.selectedText]}>{label}</Text></Pressable>)}</View>
    {profile.goal !== 'none' ? <><View style={styles.tabs}><Pressable onPress={()=>void update({calculationMode:'manual'})} style={[styles.tab,profile.calculationMode==='manual'&&styles.tabActive]}><Text style={profile.calculationMode==='manual'&&styles.tabTextActive}>Enter my targets</Text></Pressable><Pressable onPress={()=>void update({calculationMode:'calculated'})} style={[styles.tab,profile.calculationMode==='calculated'&&styles.tabActive]}><Text style={profile.calculationMode==='calculated'&&styles.tabTextActive}>Calculate for me</Text></Pressable></View>
    {profile.calculationMode==='calculated'?<View style={styles.card}><Text style={styles.section}>About you</Text><View style={styles.two}><NumericField label="Age" value={profile.age} onChange={age=>void update({age})}/><NumericField label="Height (cm)" value={profile.heightCm} onChange={heightCm=>void update({heightCm})}/></View><View style={styles.two}><NumericField label="Current weight (kg)" value={profile.currentWeightKg} onChange={currentWeightKg=>void update({currentWeightKg})}/><NumericField label="Target weight (kg)" value={profile.targetWeightKg} onChange={targetWeightKg=>void update({targetWeightKg})}/></View><Text style={styles.section}>For the energy formula</Text><View style={styles.chips}>{(['female','male'] as const).map(value=><Chip key={value} label={value==='female'?'Female':'Male'} selected={profile.sexForCalculation===value} onPress={()=>void update({sexForCalculation:value})}/>)}</View><Text style={styles.section}>Activity level</Text><View style={styles.chips}>{activities.map(([value,label])=><Chip key={value} label={label} selected={profile.activityLevel===value} onPress={()=>void update({activityLevel:value})}/>)}</View><Button label="Calculate my estimate" variant="secondary" onPress={()=>void calculate()}/></View>:null}
    <View style={styles.card}><Text style={styles.section}>Daily targets</Text><View style={styles.two}><Target label="Calories" value={String(profile.calories)} onChange={value=>void update({calories:Number(value)||0})}/><Target label="Protein (g)" value={profile.protein.replace(/[^0-9]/g,'')} onChange={value=>void update({protein:`${value} g`})}/></View><View style={styles.three}><Target label="Carbs (g)" value={profile.carbs.replace(/[^0-9]/g,'')} onChange={value=>void update({carbs:`${value} g`})}/><Target label="Fat (g)" value={profile.fat.replace(/[^0-9]/g,'')} onChange={value=>void update({fat:`${value} g`})}/><Target label="Fiber (g)" value={profile.fiber.replace(/[^0-9]/g,'')} onChange={value=>void update({fiber:`${value} g`})}/></View></View>
    <Toggle label="Use weekly average" detail="Balance targets over seven days" value={profile.weeklyAverage} onChange={weeklyAverage=>void update({weeklyAverage})}/><Toggle label="Allow flexible days" detail="Meals can vary while staying near your average" value={profile.flexibleDay} onChange={flexibleDay=>void update({flexibleDay})}/></>:null}
    {message?<Text style={styles.message}>{message}</Text>:null}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}<Text style={styles.disclaimer}>Calculated values are estimates for general wellness guidance. Consult a qualified professional for medical or therapeutic nutrition needs.</Text>
  </OnboardingShell>;
}
function NumericField({label,value,onChange}:{label:string;value?:number;onChange:(value?:number)=>void}){return <View style={styles.flex}><Field keyboardType="numeric" label={label} onChangeText={text=>onChange(numberValue(text))} value={value===undefined?'':String(value)}/></View>}
function Target({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <View style={styles.flex}><Field keyboardType="numeric" label={label} onChangeText={onChange} value={value}/></View>}
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,selected&&styles.selected]}><Text style={[styles.chipText,selected&&styles.selectedText]}>{label}</Text></Pressable>}
function Toggle({label,detail,value,onChange}:{label:string;detail:string;value:boolean;onChange:(value:boolean)=>void}){return <View style={styles.toggle}><View style={styles.flex}><Text style={styles.toggleTitle}>{label}</Text><Text style={styles.small}>{detail}</Text></View><Switch onValueChange={onChange} trackColor={{true:colors.herb}} value={value}/></View>}
const styles=StyleSheet.create({hero:{...typography.title,fontSize:25,color:colors.charcoal},body:{color:colors.muted,lineHeight:20},goalGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},goal:{width:'48.5%',minHeight:55,padding:10,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,backgroundColor:colors.paperRaised},selected:{borderColor:colors.herb,backgroundColor:colors.mintSoft},goalText:{fontWeight:'700',textAlign:'center',color:colors.charcoal},selectedText:{color:colors.herb},tabs:{flexDirection:'row',padding:4,borderRadius:radii.medium,backgroundColor:colors.lavenderSoft},tab:{flex:1,minHeight:42,alignItems:'center',justifyContent:'center',borderRadius:12},tabActive:{backgroundColor:colors.charcoal},tabTextActive:{color:colors.white,fontWeight:'800'},card:{padding:spacing.md,gap:spacing.md,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,backgroundColor:colors.paperRaised},section:{...typography.label,fontSize:16,color:colors.charcoal},two:{flexDirection:'row',gap:10},three:{flexDirection:'row',gap:8},flex:{flex:1},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:10,borderWidth:1,borderColor:colors.line,borderRadius:radii.round},chipText:{fontWeight:'700',fontSize:12},toggle:{flexDirection:'row',alignItems:'center',padding:12,borderWidth:1,borderColor:colors.line,borderRadius:radii.small,backgroundColor:colors.paperRaised},toggleTitle:{fontWeight:'800'},small:{color:colors.muted,fontSize:11},message:{padding:10,color:colors.herb,textAlign:'center',backgroundColor:colors.herbSoft,borderRadius:radii.small},error:{color:colors.coralDark,textAlign:'center'},disclaimer:{color:colors.muted,fontSize:10,lineHeight:15,textAlign:'center'}});
