import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, Screen, Title } from '@/components/ui';
import { colors, radii, spacing } from '@/theme';

export default function CommunityShareScreen() {
  const { title: initialTitle } = useLocalSearchParams<{ title?: string }>();
  const [title, setTitle] = useState(initialTitle ?? '');
  const [caption, setCaption] = useState('');
  const [shared, setShared] = useState(false);
  if (shared) return <Screen><View style={styles.success}><View style={styles.successIcon}><Ionicons color={colors.white} name="checkmark" size={36} /></View><Title>Recipe shared.</Title><Text style={styles.body}>Your kitchen inspiration is ready for the Community feed.</Text><Button label="Back to Community" onPress={() => router.replace('/community')} /></View></Screen>;
  return <Screen><ScrollView contentContainerStyle={styles.content}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={23} /></Pressable><Text style={styles.eyebrow}>SHARE WITH COMMUNITY</Text><Title>What are you keeping?</Title><Text style={styles.body}>Share a recipe, kitchen win, or helpful note with other home cooks.</Text><Card style={styles.preview}><View style={styles.previewIcon}><Ionicons color={colors.coral} name="restaurant-outline" size={36} /></View><Text style={styles.previewText}>{title.trim() || 'Your recipe title'}</Text><Text style={styles.previewBody}>{caption.trim() || 'Add a short note about why you love it.'}</Text></Card><Text style={styles.label}>Recipe title</Text><TextInput value={title} onChangeText={setTitle} placeholder="Creamy tomato pasta" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Your note</Text><TextInput multiline value={caption} onChangeText={setCaption} placeholder="Tell the community what made it a keeper..." placeholderTextColor={colors.muted} style={[styles.input, styles.textarea]} /><Button disabled={!title.trim()} label="Share recipe" onPress={() => setShared(true)} /></ScrollView></Screen>;
}
const styles=StyleSheet.create({content:{padding:spacing.lg,gap:spacing.md,paddingBottom:60},back:{width:44,height:44,borderRadius:22,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},eyebrow:{color:colors.coralDark,fontWeight:'900',letterSpacing:1.1},body:{color:colors.muted,lineHeight:21},preview:{gap:spacing.sm,backgroundColor:colors.coralSoft},previewIcon:{width:64,height:64,borderRadius:20,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},previewText:{color:colors.charcoal,fontSize:20,fontWeight:'900'},previewBody:{color:colors.muted,lineHeight:20},label:{color:colors.charcoal,fontWeight:'900',marginTop:spacing.sm},input:{minHeight:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,paddingHorizontal:spacing.md,color:colors.charcoal,backgroundColor:colors.paperRaised,fontSize:16},textarea:{minHeight:120,paddingTop:spacing.md,textAlignVertical:'top'},success:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.lg,gap:spacing.md},successIcon:{width:76,height:76,borderRadius:38,alignItems:'center',justifyContent:'center',backgroundColor:colors.herb}});
