import { compareNutritionEstimates } from '@cravekeep/domain';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Screen, SectionTitle, Title } from '@/components/ui';
import { useRecipeStore } from '@/data/recipe-store';
import { useNutritionStore } from '@/data/nutrition-store';
import { useAuthStore } from '@/data/auth-store';
import { fetchCookSessions, type CookSession } from '@/data/cook-sessions';
import { colors, radii, spacing } from '@/theme';
import { RecipeArt } from '@/components/recipe-art';

export default function RecipeDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { recipes, findRecipe, toggleFavorite, toggleCookbook } = useRecipeStore();
  const { findEstimate } = useNutritionStore();
  const { user } = useAuthStore();
  const [cookSessions, setCookSessions] = useState<CookSession[]>([]);
  const [historyError, setHistoryError] = useState(false);
  useEffect(() => {
    let active = true;
    void fetchCookSessions(id, user?.id).then((sessions) => { if (active) { setCookSessions(sessions); setHistoryError(false); } }).catch(() => { if (active) setHistoryError(true); });
    return () => { active = false; };
  }, [id, user?.id]);
  const recipe = findRecipe(id);
  if (!recipe) return <Screen style={styles.missing}><Title>Recipe not found</Title><Text style={styles.body}>It may have been removed from this device.</Text><Button label="Back to recipes" onPress={() => router.replace('/(tabs)/recipes')} /></Screen>;
  const nutrition = findEstimate(id);
  const original = recipe.originalRecipeId ? findRecipe(recipe.originalRecipeId) : undefined;
  const originalNutrition = original ? findEstimate(original.id) : undefined;
  const nutritionDifference = nutrition && originalNutrition ? compareNutritionEstimates(originalNutrition, nutrition) : undefined;
  const familyId = recipe.originalRecipeId ?? recipe.id;
  const versions = recipes.filter((item) => item.id === familyId || item.originalRecipeId === familyId).sort((a, b) => a.version - b.version);
  const latestCook = cookSessions[0];
  const averageTaste = cookSessions.length ? cookSessions.reduce((total, session) => total + session.taste, 0) / cookSessions.length : 0;
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.circle}><Ionicons name="arrow-back" size={23} /></Pressable><View style={styles.actions}>{recipe.source.kind === 'manual' && recipe.version === 1 && !recipe.originalRecipeId ? <Pressable accessibilityLabel="Edit recipe" onPress={() => router.push(`/recipes/${recipe.id}/edit`)} style={styles.circle}><Ionicons color={colors.charcoal} name="create-outline" size={23} /></Pressable> : null}<Pressable accessibilityLabel={recipe.favorite ? 'Remove favorite' : 'Favorite recipe'} onPress={() => toggleFavorite(recipe.id)} style={styles.circle}><Ionicons color={recipe.favorite ? colors.coral : colors.charcoal} name={recipe.favorite ? 'heart' : 'heart-outline'} size={23} /></Pressable></View></View>
    <RecipeArt favorite={recipe.favorite} /><Title>{recipe.title}</Title><Text style={styles.body}>{recipe.description}</Text>
    <View style={styles.versionBadge}><Ionicons color={colors.coralDark} name="git-branch-outline" size={16} /><Text style={styles.versionText}>{recipe.version === 1 ? 'Original recipe' : `Version ${recipe.version}`}</Text></View>
    {versions.length > 1 ? <Card><Text style={styles.sourceLabel}>VERSION HISTORY</Text><View style={styles.versionRow}>{versions.map((item) => <Pressable accessibilityRole="button" accessibilityState={{ selected: item.id === recipe.id }} key={item.id} onPress={() => router.replace(`/recipes/${item.id}`)} style={[styles.versionChoice, item.id === recipe.id && styles.versionChoiceActive]}><Text style={[styles.versionChoiceText, item.id === recipe.id && styles.versionChoiceTextActive]}>{item.version === 1 ? 'Original' : `V${item.version}`}</Text></Pressable>)}</View><Text style={styles.body}>Switch versions without changing or overwriting the original.</Text></Card> : null}
    <View style={styles.meta}><Text style={styles.metaText}><Ionicons name="time-outline" /> {recipe.prepMinutes + recipe.cookMinutes} min</Text><Text style={styles.metaText}><Ionicons name="people-outline" /> {recipe.servings} servings</Text><Text style={styles.private}><Ionicons name="lock-closed-outline" /> Private</Text></View>
    <Card><Text style={styles.sourceLabel}>SOURCE</Text><Text style={styles.source}>{recipe.source.label}</Text>{recipe.source.creator ? <Text style={styles.body}>By {recipe.source.creator}</Text> : null}</Card>
    <Card><Text style={styles.sourceLabel}>YOUR COOKING HISTORY</Text>{latestCook ? <><View style={styles.historySummary}><View><Text style={styles.source}>{cookSessions.length} cook{cookSessions.length === 1 ? '' : 's'}</Text><Text style={styles.body}>{averageTaste.toFixed(1)} / 5 average taste</Text></View><View style={styles.repeatBadge}><Ionicons color={latestCook.repeatIntent ? colors.herb : colors.coralDark} name={latestCook.repeatIntent ? 'refresh-circle' : 'create-outline'} size={20} /><Text style={latestCook.repeatIntent ? styles.private : styles.versionText}>{latestCook.repeatIntent ? 'Make again' : 'Adjust first'}</Text></View></View><Text style={styles.historyDate}>Latest · {new Date(latestCook.cookedAt).toLocaleDateString()} · {latestCook.effort === 'expected' ? 'Effort as expected' : latestCook.effort === 'easy' ? 'Easier than expected' : 'Harder than expected'}</Text>{latestCook.notes ? <Text style={styles.historyNotes}>“{latestCook.notes}”</Text> : null}</> : <Text style={styles.body}>{historyError ? 'History could not be refreshed from the cloud. Your device data is unchanged.' : 'Finish Cook Mode to start your private cooking history.'}</Text>}</Card>
    <Button label="Watch recipe video" variant="secondary" onPress={() => router.push(`/recipes/${recipe.id}/video` as never)} />
    <Button label={recipe.version === 1 ? 'Make it healthier' : 'Create another version'} onPress={() => router.push(`/recipes/${recipe.id}/remix`)} />
    <Card><Text style={styles.sourceLabel}>NUTRITION ESTIMATE</Text>{nutrition ? <><Text style={styles.source}>{nutrition.perServing.calories} calories · {nutrition.perServing.proteinGrams}g protein</Text><Text style={styles.body}>Per serving · {Math.round(nutrition.coverage * 100)}% coverage · {nutrition.confidence} confidence</Text>{nutritionDifference ? <Text style={styles.private}>Compared with original: {nutritionDifference.calories > 0 ? '+' : ''}{nutritionDifference.calories} cal · {nutritionDifference.proteinGrams > 0 ? '+' : ''}{nutritionDifference.proteinGrams}g protein</Text> : null}</> : <Text style={styles.body}>Review ingredient matches to calculate a transparent estimate.</Text>}<Pressable accessibilityRole="button" onPress={() => router.push(`/recipes/${recipe.id}/nutrition`)}><Text style={styles.nutritionLink}>{nutrition ? 'Review calculation' : 'Calculate nutrition'}</Text></Pressable>{nutrition ? <Pressable accessibilityRole="button" onPress={() => router.push(`/recipes/${recipe.id}/fit`)}><Text style={styles.nutritionLink}>Fit this recipe to my day</Text></Pressable> : null}</Card>
    <SectionTitle>Ingredients</SectionTitle>{recipe.ingredients.map((ingredient) => <View key={ingredient.id} style={styles.line}><View style={styles.check} /><Text style={styles.quantity}>{ingredient.quantity}</Text><Text style={styles.flexText}>{ingredient.name}</Text></View>)}
    <SectionTitle>Directions</SectionTitle>{recipe.steps.map((step, index) => <View key={`${index}-${step}`} style={styles.step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{index + 1}</Text></View><Text style={styles.flexText}>{step}</Text></View>)}
    <Button label="Start cooking" onPress={() => router.push(`/cook/${recipe.id}`)} />
    <Button label={recipe.cookbookIds.includes('weeknight') ? 'Remove from Weeknight Wins' : 'Add to Weeknight Wins'} variant="secondary" onPress={() => toggleCookbook(recipe.id, 'weeknight')} />
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, gap: spacing.md, paddingBottom: 60 }, header: { flexDirection: 'row', justifyContent: 'space-between' }, actions: { flexDirection: 'row', gap: spacing.sm }, circle: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, art: { height: 220, borderRadius: radii.large, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.mintSoft }, body: { color: colors.muted, lineHeight: 22 }, nutritionLink: { color: colors.coralDark, fontWeight: '900', marginTop: spacing.sm }, versionBadge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingHorizontal: spacing.sm, paddingVertical: 6, borderRadius: radii.round, backgroundColor: colors.lavenderSoft }, versionText: { color: colors.coralDark, fontSize: 12, fontWeight: '800' }, versionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginVertical: spacing.sm }, versionChoice: { borderWidth: 1, borderColor: colors.line, borderRadius: radii.round, paddingHorizontal: 14, paddingVertical: 8 }, versionChoiceActive: { backgroundColor: colors.coral, borderColor: colors.coral }, versionChoiceText: { color: colors.charcoal, fontWeight: '800' }, versionChoiceTextActive: { color: colors.white }, historySummary: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.sm }, repeatBadge: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, historyDate: { color: colors.muted, fontSize: 13, marginTop: spacing.sm }, historyNotes: { color: colors.charcoal, fontStyle: 'italic', lineHeight: 21, marginTop: spacing.sm }, meta: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, metaText: { color: colors.charcoal, fontWeight: '700' }, private: { color: colors.herb, fontWeight: '700' }, sourceLabel: { color: colors.coralDark, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, source: { color: colors.charcoal, fontSize: 17, fontWeight: '800' }, line: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.line }, check: { width: 20, height: 20, borderRadius: 10, borderWidth: 1, borderColor: colors.muted }, quantity: { minWidth: 62, color: colors.charcoal, fontWeight: '700' }, flexText: { flex: 1, color: colors.charcoal, fontSize: 16, lineHeight: 23 }, step: { flexDirection: 'row', gap: spacing.md, alignItems: 'flex-start', paddingVertical: spacing.sm }, stepNumber: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.coral, alignItems: 'center', justifyContent: 'center' }, stepNumberText: { color: colors.white, fontWeight: '800' }, missing: { padding: spacing.lg, justifyContent: 'center', gap: spacing.lg } });
