import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { PropsWithChildren, ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { OnboardingProgress } from './onboarding-progress';
import { colors, radii, spacing, typography } from '@/theme';

export function OnboardingShell({ title, percent, children, footer }: PropsWithChildren<{ title: string; percent: number; footer?: ReactNode }>) {
  return <SafeAreaView edges={['top', 'bottom']} style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} /></Pressable><Text style={styles.title}>{title}</Text><Text style={styles.percent}>{percent}%</Text></View><OnboardingProgress label="Onboarding" percent={percent} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{children}</ScrollView>{footer ? <View style={styles.footer}>{footer}</View> : null}</SafeAreaView>;
}
export function SettingRow({ icon, title, value, onPress, danger = false }: { icon?: keyof typeof Ionicons.glyphMap; title: string; value?: string; onPress?: () => void; danger?: boolean }) { return <Pressable disabled={!onPress} onPress={onPress} style={styles.row}>{icon ? <Ionicons color={danger ? colors.coralDark : colors.muted} name={icon} size={18} /> : null}<Text style={[styles.rowTitle, danger && styles.danger]}>{title}</Text>{value ? <Text numberOfLines={1} style={styles.value}>{value}</Text> : null}{onPress ? <Ionicons color={colors.muted} name="chevron-forward" size={16} /> : null}</Pressable>; }
export function Panel({ children }: PropsWithChildren) { return <View style={styles.panel}>{children}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: spacing.md, backgroundColor: colors.paper }, header: { height: 48, flexDirection: 'row', alignItems: 'center' }, back: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, title: { flex: 1, marginLeft: 10, color: colors.charcoal, ...typography.title, fontSize: 21, textAlign: 'center' }, percent: { width: 40, color: colors.coralDark, fontWeight: '800', textAlign: 'right' }, content: { gap: spacing.md, paddingVertical: spacing.md, paddingBottom: 28 }, footer: { paddingVertical: spacing.sm }, panel: { overflow: 'hidden', borderWidth: 1, borderColor: colors.line, borderRadius: radii.medium, backgroundColor: colors.paperRaised }, row: { minHeight: 50, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, rowTitle: { flex: 1, color: colors.charcoal, fontWeight: '700' }, value: { maxWidth: '42%', color: colors.muted, fontSize: 12 }, danger: { color: colors.coralDark } });
